export const supportedLanguages = [
  { code: "en-US", lang: "English (US)" },
  { code: "en-GB", lang: "English (UK)" },
  { code: "es-ES", lang: "Spanish (Spain)" },
  { code: "es-419", lang: "Spanish (LatAm)" },
  { code: "fr", lang: "French" },
  { code: "de", lang: "German" },
  { code: "pt-BR", lang: "Portuguese (Brazil)" },
  { code: "it", lang: "Italian" },
  { code: "ja", lang: "Japanese" },
  { code: "ko", lang: "Korean" },
  { code: "nl", lang: "Dutch" },
  { code: "sv-SE", lang: "Swedish" },
  { code: "fi", lang: "Finnish" },
  { code: "pl", lang: "Polish" },
  { code: "ru", lang: "Russian" },
  { code: "tr", lang: "Turkish" },
  { code: "th", lang: "Thai" },
  { code: "vi", lang: "Vietnamese" },
  { code: "uk", lang: "Ukrainian" },
  { code: "el", lang: "Greek" },
  { code: "hu", lang: "Hungarian" },
  { code: "ro", lang: "Romanian" },
  { code: "cs", lang: "Czech" },
  { code: "da", lang: "Danish" },
  { code: "no", lang: "Norwegian" },
  { code: "lt", lang: "Lithuanian" },
];
