const emojiArray = [
  {
    categoryText: "People",
    value: "people",
    emojis: [
      { text: "😀", shortCode: ":grinning:", value: "😀", searchKeywords: ["happy", "smile", "grinning", "face", "cheerful", "joy", "glad", "pleased"] },
      { text: "😃", shortCode: ":smiley:", value: "😃", searchKeywords: ["happy", "smile", "smiley", "face", "cheerful", "joy", "glad", "excited"] },
      { text: "😄", shortCode: ":smile:", value: "😄", searchKeywords: ["happy", "smile", "grin", "face", "cheerful", "joy", "glad", "pleased"] },
      { text: "😁", shortCode: ":grin:", value: "😁", searchKeywords: ["happy", "grin", "face", "teeth", "cheeky", "smile", "joy", "mischievous"] },
      { text: "😂", shortCode: ":joy:", value: "😂", searchKeywords: ["laugh", "tears", "joy", "funny", "haha", "lol", "comedy", "humor"] },
      { text: "🤣", shortCode: ":rofl:", value: "🤣", searchKeywords: ["laugh", "rofl", "rolling", "funny", "haha", "lol", "comedy", "hysterical"] },
      { text: "🙂", shortCode: ":slightly_smiling_face:", value: "🙂", searchKeywords: ["smile", "face", "content", "okay", "fine", "slight", "subtle", "calm"] },
      { text: "😉", shortCode: ":wink:", value: "😉", searchKeywords: ["wink", "face", "flirt", "joking", "teasing", "playful", "sly", "knowing"] },
      { text: "😊", shortCode: ":blush:", value: "😊", searchKeywords: ["happy", "smile", "blush", "face", "shy", "pleased", "content", "grateful"] },
      { text: "😍", shortCode: ":heart_eyes:", value: "😍", searchKeywords: ["love", "heart", "eyes", "adoration", "crush", "infatuated", "enamored", "admire"] },
      { text: "😘", shortCode: ":kissing_heart:", value: "😘", searchKeywords: ["kiss", "love", "heart", "affection", "romance", "intimate", "passion", "adore"] },
      { text: "😜", shortCode: ":stuck_out_tongue_winking_eye:", value: "😜" },
      { text: "😝", shortCode: ":stuck_out_tongue_closed_eyes:", value: "😝", searchKeywords: ["tongue", "silly", "playful", "joking", "teasing", "fun", "mischievous", "goofy"] },
      { text: "😒", shortCode: ":unamused:", value: "😒", searchKeywords: ["unamused", "annoyed", "bored", "disappointed", "skeptical", "doubtful", "unimpressed", "meh"] },
      { text: "🤔", shortCode: ":thinking:", value: "🤔", searchKeywords: ["thinking", "ponder", "wonder", "curious", "contemplating", "considering", "reflecting", "puzzled"] },
      { text: "🙄", shortCode: ":roll_eyes:", value: "🙄", searchKeywords: ["eyeroll", "annoyed", "frustrated", "disappointed", "skeptical", "disbelief", "whatever", "bored"] },
      { text: "😭", shortCode: ":sob:", value: "😭", searchKeywords: ["cry", "tears", "sad", "upset", "distraught", "heartbroken", "grief", "sorrow"] },
      { text: "😩", shortCode: ":weary:", value: "😩", searchKeywords: ["weary", "tired", "exhausted", "frustrated", "drained", "fatigued", "overwhelmed", "stressed"] },
      { text: "😡", shortCode: ":rage:", value: "😡", searchKeywords: ["angry", "mad", "rage", "furious", "outraged", "irate", "livid", "annoyed"] },
      { text: "👍", shortCode: ":thumbsup:", value: "👍", searchKeywords: ["thumbs", "up", "good", "yes", "like", "approve", "agree", "ok"] },
      { text: "👎", shortCode: ":thumbsdown:", value: "👎", searchKeywords: ["thumbs", "down", "bad", "no", "dislike", "disapprove", "disagree", "reject"] },
      { text: "🙌", shortCode: ":raised_hands:", value: "🙌", searchKeywords: ["hands", "up", "celebrate", "praise", "hooray", "yay", "excited", "joy"] },
      { text: "🙏", shortCode: ":pray:", value: "🙏", searchKeywords: ["pray", "please", "hope", "thanks", "grateful", "wish", "blessing", "amen"] },
      { text: "👏", shortCode: ":clap:", value: "👏", searchKeywords: ["clap", "applause", "praise", "congratulations", "bravo", "well done", "approval", "celebration"] },
      { text: "🤷‍♂️", shortCode: ":man_shrugging:", value: "🤷‍♂️", searchKeywords: ["shrug", "confused", "uncertain", "dunno", "whatever", "helpless", "puzzled", "bewildered"] },
      { text: "🤦‍♀️", shortCode: ":woman_facepalming:", value: "🤦‍♀️", searchKeywords: ["facepalm", "disappointed", "frustrated", "embarrassed", "stupid", "really", "ugh", "annoyed"] },
      { text: "🤞", shortCode: ":crossed_fingers:", value: "🤞", searchKeywords: ["fingers", "crossed", "luck", "hope", "wish", "praying", "optimistic", "fortune"] },
      { text: "💯", shortCode: ":100:", value: "💯", searchKeywords: ["100", "perfect", "score", "hundred", "excellent", "amazing", "awesome", "complete"] },
      { text: "🤩", shortCode: ":star_struck:", value: "🤩", searchKeywords: ["star", "struck", "amazed", "impressed", "wow", "awesome", "brilliant", "excited"] },
      { text: "🥳", shortCode: ":partying_face:", value: "🥳", searchKeywords: ["party", "celebration", "fun", "excited", "festive", "cheerful", "joy", "celebrate"] },
      { text: "😎", shortCode: ":sunglasses:", value: "😎", searchKeywords: ["cool", "sunglasses", "swag", "confident", "stylish", "awesome", "chill", "relaxed"] },
      { text: "🤓", shortCode: ":nerd_face:", value: "🤓", searchKeywords: ["nerd", "smart", "geek", "studious", "intelligent", "bookworm", "glasses", "brainy"] },
      { text: "🧐", shortCode: ":monocle_face:", value: "🧐", searchKeywords: ["monocle", "investigating", "scrutinizing", "examining", "curious", "detective", "suspicious", "analytical"] },
      { text: "😇", shortCode: ":innocent:", value: "😇", searchKeywords: ["innocent", "angel", "pure", "good", "halo", "saintly", "virtuous", "kind"] },
      { text: "🥰", shortCode: ":smiling_face_with_three_hearts:", value: "🥰", searchKeywords: ["love", "hearts", "happy", "affection", "adoration", "crush", "romance", "in love"] },
      { text: "😋", shortCode: ":yum:", value: "😋", searchKeywords: ["yum", "delicious", "tasty", "food", "eating", "savoring", "flavor", "yummy"] },
      { text: "😛", shortCode: ":stuck_out_tongue:", value: "😛", searchKeywords: ["tongue", "playful", "silly", "joking", "teasing", "fun", "mischievous", "goofy"] },
      { text: "😜", shortCode: ":stuck_out_tongue_winking_eye:", value: "😜", searchKeywords: ["tongue", "wink", "playful", "silly", "joking", "teasing", "mischievous", "fun"] },
      { text: "🤪", shortCode: ":zany_face:", value: "🤪", searchKeywords: ["zany", "crazy", "wacky", "silly", "goofy", "wild", "nuts", "bonkers"] },
      { text: "😴", shortCode: ":sleeping:", value: "😴", searchKeywords: ["sleeping", "sleepy", "tired", "bedtime", "rest", "nap", "slumber", "drowsy"] },
      { text: "😪", shortCode: ":sleepy:", value: "😪", searchKeywords: ["sleepy", "tired", "exhausted", "yawning", "drowsy", "fatigued", "weary", "sleeping"] },
      { text: "😵", shortCode: ":dizzy_face:", value: "😵", searchKeywords: ["dizzy", "confused", "disoriented", "lightheaded", "woozy", "stunned", "bewildered", "groggy"] },
    ],
  },
  {
    categoryText: "Nature",
    value: "nature",
    emojis: [
      { text: "🐶", shortCode: ":dog:", value: "🐶", searchKeywords: ["dog", "puppy", "canine", "pet", "animal", "loyal", "friend", "bark"] },
      { text: "🐱", shortCode: ":cat:", value: "🐱", searchKeywords: ["cat", "kitten", "feline", "pet", "animal", "meow", "cute", "independent"] },
      { text: "🐭", shortCode: ":mouse:", value: "🐭", searchKeywords: ["mouse", "rodent", "small", "animal", "tiny", "squeak", "cheese", "cute"] },
      { text: "🐹", shortCode: ":hamster:", value: "🐹", searchKeywords: ["hamster", "rodent", "pet", "small", "fluffy", "cute", "wheel", "gnaw"] },
      { text: "🐰", shortCode: ":rabbit:", value: "🐰", searchKeywords: ["rabbit", "bunny", "hop", "animal", "cute", "fluffy", "carrot", "fast"] },
      { text: "🦊", shortCode: ":fox_face:", value: "🦊", searchKeywords: ["fox", "clever", "animal", "wild", "sly", "orange", "bushy", "cunning"] },
      { text: "🐻", shortCode: ":bear:", value: "🐻", searchKeywords: ["bear", "grizzly", "animal", "wild", "strong", "brown", "hibernate", "roar"] },
      { text: "🐼", shortCode: ":panda_face:", value: "🐼", searchKeywords: ["panda", "bamboo", "bear", "animal", "cute", "black", "white", "china"] },
      { text: "🐨", shortCode: ":koala:", value: "🐨", searchKeywords: ["koala", "australia", "animal", "cute", "eucalyptus", "tree", "marsupial", "sleepy"] },
      { text: "🐯", shortCode: ":tiger:", value: "🐯", searchKeywords: ["tiger", "stripes", "animal", "wild", "fierce", "orange", "black", "roar"] },
      { text: "🐮", shortCode: ":cow:", value: "🐮", searchKeywords: ["cow", "moo", "farm", "animal", "milk", "grass", "pasture", "bull"] },
      { text: "🐷", shortCode: ":pig:", value: "🐷", searchKeywords: ["pig", "oink", "farm", "animal", "pink", "mud", "snout", "bacon"] },
      { text: "🐸", shortCode: ":frog:", value: "🐸", searchKeywords: ["frog", "ribbit", "amphibian", "green", "hop", "pond", "lily", "croak"] },
      { text: "🐵", shortCode: ":monkey_face:", value: "🐵", searchKeywords: ["monkey", "ape", "banana", "animal", "swing", "tree", "chatter", "primate"] },
      { text: "🐔", shortCode: ":chicken:", value: "🐔", searchKeywords: ["chicken", "rooster", "hen", "farm", "bird", "cluck", "egg", "poultry"] },
      { text: "🐧", shortCode: ":penguin:", value: "🐧", searchKeywords: ["penguin", "antarctica", "bird", "cold", "ice", "waddle", "tuxedo", "swim"] },
      { text: "🐦", shortCode: ":bird:", value: "🐦", searchKeywords: ["bird", "fly", "tweet", "animal", "feather", "wing", "nest", "chirp"] },
      { text: "🐝", shortCode: ":bee:", value: "🐝", searchKeywords: ["bee", "honey", "buzz", "insect", "sting", "hive", "pollen", "queen"] },
      { text: "🐛", shortCode: ":bug:", value: "🐛", searchKeywords: ["bug", "insect", "caterpillar", "crawl", "small", "worm", "garden", "pest"] },
      { text: "🦋", shortCode: ":butterfly:", value: "🦋", searchKeywords: ["butterfly", "beautiful", "insect", "wing", "colorful", "flutter", "garden", "transformation"] },
      { text: "🌸", shortCode: ":cherry_blossom:", value: "🌸", searchKeywords: ["flower", "cherry", "blossom", "spring", "pink", "petal", "japan", "sakura"] },
      { text: "🌼", shortCode: ":blossom:", value: "🌼", searchKeywords: ["flower", "blossom", "plant", "garden", "yellow", "white", "daisy", "nature"] },
      { text: "🌻", shortCode: ":sunflower:", value: "🌻", searchKeywords: ["sunflower", "flower", "yellow", "sun", "tall", "summer", "garden", "bright"] },
      { text: "🌺", shortCode: ":hibiscus:", value: "🌺", searchKeywords: ["hibiscus", "flower", "tropical", "pink", "red", "hawaii", "exotic", "bloom"] },
      { text: "🌱", shortCode: ":seedling:", value: "🌱", searchKeywords: ["seedling", "plant", "growth", "green", "sprout", "nature", "garden", "new"] },
      { text: "🌲", shortCode: ":evergreen_tree:", value: "🌲", searchKeywords: ["tree", "evergreen", "forest", "pine", "nature", "wood", "green", "christmas"] },
      { text: "☀️", shortCode: ":sunny:", value: "☀️", searchKeywords: ["sun", "sunny", "bright", "warm", "day", "light", "summer", "weather"] },
      { text: "🌧️", shortCode: ":cloud_with_rain:", value: "🌧️", searchKeywords: ["rain", "cloud", "storm", "wet", "weather", "umbrella", "shower", "precipitation"] },
      { text: "⛈️", shortCode: ":lightning_cloud:", value: "⛈️", searchKeywords: ["lightning", "storm", "thunder", "electric", "weather", "dark", "flash", "dangerous"] },
      { text: "🌩️", shortCode: ":cloud_with_lightning:", value: "🌩️", searchKeywords: ["lightning", "cloud", "storm", "thunder", "weather", "electric", "flash", "power"] },
      { text: "🌨️", shortCode: ":cloud_with_snow:", value: "🌨️", searchKeywords: ["snow", "cloud", "winter", "cold", "weather", "flake", "freeze", "white"] },
      { text: "☁️", shortCode: ":cloud:", value: "☁️", searchKeywords: ["cloud", "sky", "weather", "white", "fluffy", "overcast", "gray", "float"] },
      { text: "🌤️", shortCode: ":sun_behind_small_cloud:", value: "🌤️", searchKeywords: ["sun", "cloud", "partly", "sunny", "weather", "nice", "day", "bright"] },
      { text: "🌥️", shortCode: ":sun_behind_large_cloud:", value: "🌥️", searchKeywords: ["sun", "cloud", "overcast", "weather", "gray", "dim", "hazy", "gloomy"] },
      { text: "🌦️", shortCode: ":sun_behind_rain_cloud:", value: "🌦️", searchKeywords: ["sun", "rain", "cloud", "weather", "shower", "storm", "wet", "rainbow"] },
      { text: "🌈", shortCode: ":rainbow:", value: "🌈", searchKeywords: ["rainbow", "colorful", "colors", "sky", "weather", "storm", "pride", "beautiful"] },
      { text: "⭐", shortCode: ":star2:", value: "⭐", searchKeywords: ["star", "night", "sky", "twinkle", "bright", "celestial", "space", "shine"] },
      { text: "🌟", shortCode: ":glowing_star:", value: "🌟", searchKeywords: ["star", "glowing", "bright", "shining", "sparkle", "celestial", "night", "amazing"] },
      { text: "💫", shortCode: ":dizzy:", value: "💫", searchKeywords: ["dizzy", "sparkle", "star", "magic", "cosmic", "space", "twinkle", "motion"] },
      { text: "☄️", shortCode: ":comet:", value: "☄️", searchKeywords: ["comet", "space", "asteroid", "meteor", "cosmic", "tail", "flying", "celestial"] },
      { text: "🌙", shortCode: ":crescent_moon:", value: "🌙", searchKeywords: ["moon", "night", "crescent", "sky", "sleep", "dark", "celestial", "space"] },
      { text: "🌍", shortCode: ":earth_americas:", value: "🌍", searchKeywords: ["earth", "world", "globe", "planet", "america", "blue", "space", "global"] },
    ],
  },
  {
    categoryText: "Food",
    value: "food",
    emojis: [
      { text: "🍏", shortCode: ":green_apple:", value: "🍏" },
      { text: "🍎", shortCode: ":apple:", value: "🍎" },
      { text: "🍐", shortCode: ":pear:", value: "🍐" },
      { text: "🍊", shortCode: ":tangerine:", value: "🍊" },
      { text: "🍋", shortCode: ":lemon:", value: "🍋" },
      { text: "🍌", shortCode: ":banana:", value: "🍌" },
      { text: "🍉", shortCode: ":watermelon:", value: "🍉" },
      { text: "🍇", shortCode: ":grapes:", value: "🍇" },
      { text: "🍓", shortCode: ":strawberry:", value: "🍓" },
      { text: "🍒", shortCode: ":cherries:", value: "🍒" },
      { text: "🍑", shortCode: ":peach:", value: "🍑" },
      { text: "🍍", shortCode: ":pineapple:", value: "🍍" },
      { text: "🥭", shortCode: ":mango:", value: "🥭" },
      { text: "🍅", shortCode: ":tomato:", value: "🍅" },
      { text: "🍆", shortCode: ":eggplant:", value: "🍆" },
      { text: "🥑", shortCode: ":avocado:", value: "🥑" },
      { text: "🥦", shortCode: ":broccoli:", value: "🥦" },
      { text: "🥕", shortCode: ":carrot:", value: "🥕" },
      { text: "🌽", shortCode: ":corn:", value: "🌽" },
      { text: "🌶️", shortCode: ":hot_pepper:", value: "🌶️" },
      { text: "🥐", shortCode: ":croissant:", value: "🥐" },
      { text: "🍞", shortCode: ":bread:", value: "🍞" },
      { text: "🧀", shortCode: ":cheese:", value: "🧀" },
      { text: "🍗", shortCode: ":poultry_leg:", value: "🍗" },
      { text: "🍖", shortCode: ":meat_on_bone:", value: "🍖" },
      { text: "🍔", shortCode: ":hamburger:", value: "🍔" },
      { text: "🍟", shortCode: ":fries:", value: "🍟" },
      { text: "🍕", shortCode: ":pizza:", value: "🍕" },
      { text: "🍣", shortCode: ":sushi:", value: "🍣" },
      { text: "☕️", shortCode: ":coffee:", value: "☕️" },
      { text: "🍺", shortCode: ":beer:", value: "🍺" },
      { text: "🍷", shortCode: ":wine_glass:", value: "🍷" },
      { text: "🥤", shortCode: ":cup_with_straw:", value: "🥤" },
      { text: "🧃", shortCode: ":juice_box:", value: "🧃" },
      { text: "🧉", shortCode: ":mate:", value: "🧉" },
      { text: "🥂", shortCode: ":clinking_glasses:", value: "🥂" },
      { text: "🥃", shortCode: ":tumbler_glass:", value: "🥃" },
      { text: "🥘", shortCode: ":shallow_pan_of_food:", value: "🥘" },
      { text: "🍲", shortCode: ":pot_of_food:", value: "🍲" },
      { text: "🥣", shortCode: ":cereal:", value: "🥣" },
      { text: "🥗", shortCode: ":salad:", value: "🥗" },
      { text: "🍿", shortCode: ":popcorn:", value: "🍿" },
      { text: "🧈", shortCode: ":butter:", value: "🧈" },
      { text: "🧂", shortCode: ":salt:", value: "🧂" },
      { text: "🥫", shortCode: ":canned_food:", value: "🥫" },
      { text: "🦐", shortCode: ":shrimp:", value: "🦐" },
      { text: "🦀", shortCode: ":crab:", value: "🦀" },
    ],
  },
  {
    categoryText: "Activities",
    value: "activities",
    emojis: [
      { text: "⚽️", shortCode: ":soccer:", value: "⚽️" },
      { text: "🏀", shortCode: ":basketball:", value: "🏀" },
      { text: "🏈", shortCode: ":football:", value: "🏈" },
      { text: "⚾️", shortCode: ":baseball:", value: "⚾️" },
      { text: "🎾", shortCode: ":tennis:", value: "🎾" },
      { text: "🏐", shortCode: ":volleyball:", value: "🏐" },
      { text: "🏉", shortCode: ":rugby_football:", value: "🏉" },
      { text: "🎱", shortCode: ":8ball:", value: "🎱" },
      { text: "🏓", shortCode: ":ping_pong:", value: "🏓" },
      { text: "🏸", shortCode: ":badminton:", value: "🏸" },
      { text: "🥊", shortCode: ":boxing_glove:", value: "🥊" },
      { text: "🥋", shortCode: ":martial_arts_uniform:", value: "🥋" },
      { text: "⛳️", shortCode: ":golf:", value: "⛳️" },
      { text: "🏹", shortCode: ":bow_and_arrow:", value: "🏹" },
      { text: "🎣", shortCode: ":fishing_pole_and_fish:", value: "🎣" },
      { text: "🏆", shortCode: ":trophy:", value: "🏆" },
      { text: "🎮", shortCode: ":video_game:", value: "🎮" },
      { text: "🎲", shortCode: ":game_die:", value: "🎲" },
      { text: "🎯", shortCode: ":dart:", value: "🎯" },
      { text: "🎬", shortCode: ":clapper:", value: "🎬" },
      { text: "🎤", shortCode: ":microphone:", value: "🎤" },
      { text: "🎧", shortCode: ":headphones:", value: "🎧" },
      { text: "🎸", shortCode: ":guitar:", value: "🎸" },
      { text: "🎹", shortCode: ":musical_keyboard:", value: "🎹" },
      { text: "🎭", shortCode: ":performing_arts:", value: "🎭" },
      { text: "🎨", shortCode: ":art:", value: "🎨" },
      { text: "🖌️", shortCode: ":paintbrush:", value: "🖌️" },
      { text: "🖍️", shortCode: ":crayon:", value: "🖍️" },
      { text: "📝", shortCode: ":memo:", value: "📝" },
      { text: "📚", shortCode: ":books:", value: "📚" },
      { text: "📖", shortCode: ":open_book:", value: "📖" },
      { text: "🎪", shortCode: ":circus_tent:", value: "🎪" },
      { text: "🎰", shortCode: ":slot_machine:", value: "🎰" },
      { text: "🎳", shortCode: ":bowling:", value: "🎳" },
      { text: "🏂", shortCode: ":snowboarder:", value: "🏂" },
      { text: "🏋️", shortCode: ":weight_lifter:", value: "🏋️" },
      { text: "🤸", shortCode: ":person_doing_cartwheel:", value: "🤸" },
      { text: "🤺", shortCode: ":person_fencing:", value: "🤺" },
      { text: "🏇", shortCode: ":horse_racing:", value: "🏇" },
    ],
  },
  {
    categoryText: "travel",
    value: "travel",
    emojis: [
      { text: "🚗", shortCode: ":car:", value: "🚗" },
      { text: "🚕", shortCode: ":taxi:", value: "🚕" },
      { text: "🚙", shortCode: ":blue_car:", value: "🚙" },
      { text: "🚌", shortCode: ":bus:", value: "🚌" },
      { text: "🚎", shortCode: ":trolleybus:", value: "🚎" },
      { text: "🚓", shortCode: ":police_car:", value: "🚓" },
      { text: "🚑", shortCode: ":ambulance:", value: "🚑" },
      { text: "🚒", shortCode: ":fire_engine:", value: "🚒" },
      { text: "🚐", shortCode: ":minibus:", value: "🚐" },
      { text: "🚚", shortCode: ":truck:", value: "🚚" },
      { text: "🚛", shortCode: ":articulated_lorry:", value: "🚛" },
      { text: "🚜", shortCode: ":tractor:", value: "🚜" },
      { text: "🚲", shortCode: ":bicycle:", value: "🚲" },
      { text: "🛴", shortCode: ":scooter:", value: "🛴" },
      { text: "🏍️", shortCode: ":motorcycle:", value: "🏍️" },
      { text: "🛵", shortCode: ":motor_scooter:", value: "🛵" },
      { text: "🚢", shortCode: ":ship:", value: "🚢" },
      { text: "✈️", shortCode: ":airplane:", value: "✈️" },
      { text: "🛩️", shortCode: ":small_airplane:", value: "🛩️" },
      { text: "🚀", shortCode: ":rocket:", value: "🚀" },
      { text: "🗺️", shortCode: ":world_map:", value: "🗺️" },
      { text: "🗽", shortCode: ":statue_of_liberty:", value: "🗽" },
      { text: "🗼", shortCode: ":tokyo_tower:", value: "🗼" },
      { text: "🏝️", shortCode: ":island:", value: "🏝️" },
      { text: "🏖️", shortCode: ":beach_with_umbrella:", value: "🏖️" },
      { text: "🏕️", shortCode: ":camping:", value: "🏕️" },
      { text: "🏞️", shortCode: ":national_park:", value: "🏞️" },
      { text: "🌃", shortCode: ":night_with_stars:", value: "🌃" },
      { text: "🏙️", shortCode: ":cityscape:", value: "🏙️" },
      { text: "🌄", shortCode: ":sunrise_over_mountains:", value: "🌄" },
      { text: "🌅", shortCode: ":sunrise:", value: "🌅" },
      { text: "🌆", shortCode: ":cityscape_at_dusk:", value: "🌆" },
      { text: "🌇", shortCode: ":sunset:", value: "🌇" },
      { text: "🌉", shortCode: ":bridge_at_night:", value: "🌉" },
      { text: "♨️", shortCode: ":hotsprings:", value: "♨️" },
      { text: "🎠", shortCode: ":carousel_horse:", value: "🎠" },
      { text: "🎡", shortCode: ":ferris_wheel:", value: "🎡" },
      { text: "🎢", shortCode: ":roller_coaster:", value: "🎢" },
      { text: "💒", shortCode: ":wedding:", value: "💒" },
    ],
  },
  {
    categoryText: "Objects",
    value: "objects",
    emojis: [
      { text: "🔑", shortCode: ":key:", value: "🔑" },
      { text: "🧭", shortCode: ":compass:", value: "🧭" },
      { text: "🧰", shortCode: ":toolbox:", value: "🧰" },
      { text: "🛠️", shortCode: ":hammer_and_wrench:", value: "🛠️" },
      { text: "🔨", shortCode: ":hammer:", value: "🔨" },
      { text: "🔧", shortCode: ":wrench:", value: "🔧" },
      { text: "🔩", shortCode: ":nut_and_bolt:", value: "🔩" },
      { text: "⚙️", shortCode: ":gear:", value: "⚙️" },
      { text: "💡", shortCode: ":bulb:", value: "💡" },
      { text: "🔦", shortCode: ":flashlight:", value: "🔦" },
      { text: "🧯", shortCode: ":fire_extinguisher:", value: "🧯" },
      { text: "🧪", shortCode: ":test_tube:", value: "🧪" },
      { text: "🔬", shortCode: ":microscope:", value: "🔬" },
      { text: "🧬", shortCode: ":dna:", value: "🧬" },
      { text: "🖥️", shortCode: ":desktop_computer:", value: "🖥️" },
      { text: "💻", shortCode: ":laptop:", value: "💻" },
      { text: "🖨️", shortCode: ":printer:", value: "🖨️" },
      { text: "🖱️", shortCode: ":computer_mouse:", value: "🖱️" },
      { text: "📱", shortCode: ":iphone:", value: "📱" },
      { text: "📷", shortCode: ":camera:", value: "📷" },
      { text: "🎥", shortCode: ":movie_camera:", value: "🎥" },
      { text: "📺", shortCode: ":tv:", value: "📺" },
      { text: "📦", shortCode: ":package:", value: "📦" },
      { text: "⏰", shortCode: ":alarm_clock:", value: "⏰" },
      { text: "📱", shortCode: ":iphone:", value: "📱" },
      { text: "⌚", shortCode: ":watch:", value: "⌚" },
      { text: "📻", shortCode: ":radio:", value: "📻" },
      { text: "📡", shortCode: ":satellite:", value: "📡" },
      { text: "🔋", shortCode: ":battery:", value: "🔋" },
      { text: "🔌", shortCode: ":electric_plug:", value: "🔌" },
      { text: "💳", shortCode: ":credit_card:", value: "💳" },
      { text: "💸", shortCode: ":money_with_wings:", value: "💸" },
      { text: "💰", shortCode: ":moneybag:", value: "💰" },
      { text: "💴", shortCode: ":yen:", value: "💴" },
      { text: "💵", shortCode: ":dollar:", value: "💵" },
      { text: "💶", shortCode: ":euro:", value: "💶" },
      { text: "💷", shortCode: ":pound:", value: "💷" },
      { text: "🪙", shortCode: ":coin:", value: "🪙" },
    ],
  },
  {
    categoryText: "Symbols",
    value: "symbols",
    emojis: [
      { text: "❤️", shortCode: ":heart:", value: "❤️" },
      { text: "💛", shortCode: ":yellow_heart:", value: "💛" },
      { text: "💚", shortCode: ":green_heart:", value: "💚" },
      { text: "💙", shortCode: ":blue_heart:", value: "💙" },
      { text: "💜", shortCode: ":purple_heart:", value: "💜" },
      { text: "🖤", shortCode: ":black_heart:", value: "🖤" },
      { text: "💔", shortCode: ":broken_heart:", value: "💔" },
      { text: "🔥", shortCode: ":fire:", value: "🔥" },
      { text: "⭐️", shortCode: ":star:", value: "⭐️" },
      { text: "✨", shortCode: ":sparkles:", value: "✨" },
      { text: "⚡️", shortCode: ":zap:", value: "⚡️" },
      { text: "⭕️", shortCode: ":o:", value: "⭕️" },
      { text: "✅", shortCode: ":white_check_mark:", value: "✅" },
      { text: "❌", shortCode: ":x:", value: "❌" },
      { text: "➕", shortCode: ":heavy_plus_sign:", value: "➕" },
      { text: "➖", shortCode: ":heavy_minus_sign:", value: "➖" },
      { text: "♻️", shortCode: ":recycle:", value: "♻️" },
      { text: "💯", shortCode: ":100:", value: "💯" },
      { text: "🔁", shortCode: ":repeat:", value: "🔁" },
      { text: "🔃", shortCode: ":repeat_one:", value: "🔃" },
      { text: "♈️", shortCode: ":aries:", value: "♈️" },
      { text: "♉️", shortCode: ":taurus:", value: "♉️" },
      { text: "♊️", shortCode: ":gemini:", value: "♊️" },
      { text: "♋️", shortCode: ":cancer:", value: "♋️" },
      { text: "♌️", shortCode: ":leo:", value: "♌️" },
      { text: "♍️", shortCode: ":virgo:", value: "♍️" },
      { text: "♎️", shortCode: ":libra:", value: "♎️" },
      { text: "♏️", shortCode: ":scorpius:", value: "♏️" },
      { text: "♐️", shortCode: ":sagittarius:", value: "♐️" },
      { text: "♑️", shortCode: ":capricorn:", value: "♑️" },
      { text: "♒️", shortCode: ":aquarius:", value: "♒️" },
      { text: "♓️", shortCode: ":pisces:", value: "♓️" },
      { text: "🆔", shortCode: ":id:", value: "🆔" },
      { text: "🆚", shortCode: ":vs:", value: "🆚" },
      { text: "📶", shortCode: ":signal_strength:", value: "📶" },
      { text: "🎯", shortCode: ":dart:", value: "🎯" },
      { text: "🔱", shortCode: ":trident:", value: "🔱" },
      { text: "⚠️", shortCode: ":warning:", value: "⚠️" },
      { text: "🚸", shortCode: ":children_crossing:", value: "🚸" },
      { text: "🔞", shortCode: ":underage:", value: "🔞" },
    ],
  },
  {
    categoryText: "Flags",
    value: "flags",
    emojis: [
      { text: "🇺🇸", shortCode: ":flag_us:", value: "🇺🇸", searchKeywords: ["usa", "america", "united states", "us", "north america", "washington", "american"] },
      { text: "🇬🇧", shortCode: ":flag_gb:", value: "🇬🇧", searchKeywords: ["uk", "britain", "united kingdom", "england", "london", "british", "europe"] },
      { text: "🇨🇦", shortCode: ":flag_ca:", value: "🇨🇦", searchKeywords: ["canada", "canadian", "north america", "ottawa", "maple", "hockey", "toronto"] },
      { text: "🇩🇪", shortCode: ":flag_de:", value: "🇩🇪", searchKeywords: ["germany", "deutschland", "berlin", "europe", "german", "bmw", "beer"] },
      { text: "🇫🇷", shortCode: ":flag_fr:", value: "🇫🇷", searchKeywords: ["france", "paris", "europe", "french", "eiffel", "wine", "romance"] },
      { text: "🇪🇸", shortCode: ":flag_es:", value: "🇪🇸", searchKeywords: ["spain", "espana", "madrid", "europe", "spanish", "flamenco", "paella"] },
      { text: "🇮🇹", shortCode: ":flag_it:", value: "🇮🇹", searchKeywords: ["italy", "italia", "rome", "europe", "italian", "pizza", "pasta", "venice"] },
      { text: "🇯🇵", shortCode: ":flag_jp:", value: "🇯🇵", searchKeywords: ["japan", "tokyo", "asia", "japanese", "anime", "sushi", "samurai", "fuji"] },
      { text: "🇰🇷", shortCode: ":flag_kr:", value: "🇰🇷", searchKeywords: ["south korea", "korea", "seoul", "asia", "korean", "kpop", "bbq", "gangnam"] },
      { text: "🇨🇳", shortCode: ":flag_cn:", value: "🇨🇳", searchKeywords: ["china", "beijing", "asia", "chinese", "great wall", "communist", "shanghai"] },
      { text: "🇮🇳", shortCode: ":flag_in:", value: "🇮🇳", searchKeywords: ["india", "delhi", "asia", "indian", "taj mahal", "bollywood", "yoga", "curry"] },
      { text: "🇧🇷", shortCode: ":flag_br:", value: "🇧🇷", searchKeywords: ["brazil", "rio", "south america", "brazilian", "carnival", "samba", "soccer", "amazon"] },
      { text: "🇲🇽", shortCode: ":flag_mx:", value: "🇲🇽", searchKeywords: ["mexico", "mexican", "north america", "mexico city", "taco", "sombrero", "cancun"] },
      { text: "🇦🇺", shortCode: ":flag_au:", value: "🇦🇺", searchKeywords: ["australia", "aussie", "oceania", "sydney", "kangaroo", "koala", "outback", "melbourne"] },
      { text: "🇳🇱", shortCode: ":flag_nl:", value: "🇳🇱", searchKeywords: ["netherlands", "holland", "amsterdam", "europe", "dutch", "tulip", "windmill", "bike"] },
      { text: "🇸🇪", shortCode: ":flag_se:", value: "🇸🇪", searchKeywords: ["sweden", "stockholm", "europe", "swedish", "nordic", "ikea", "meatballs", "volvo"] },
      { text: "🇷🇺", shortCode: ":flag_ru:", value: "🇷🇺", searchKeywords: ["russia", "moscow", "europe", "russian", "kremlin", "vodka", "matryoshka", "putin"] },
      { text: "🇹🇷", shortCode: ":flag_tr:", value: "🇹🇷", searchKeywords: ["turkey", "istanbul", "europe", "turkish", "ottoman", "kebab", "bosphorus", "ankara"] },
      { text: "🇸🇦", shortCode: ":flag_sa:", value: "🇸🇦", searchKeywords: ["saudi arabia", "mecca", "middle east", "arabian", "oil", "islam", "ryadh", "desert"] },
      { text: "🇿🇦", shortCode: ":flag_za:", value: "🇿🇦", searchKeywords: ["south africa", "africa", "johannesburg", "cape town", "mandela", "rainbow nation"] },
      { text: "🇦🇷", shortCode: ":flag_ar:", value: "🇦🇷", searchKeywords: ["argentina", "buenos aires", "south america", "argentine", "tango", "maradona", "messi", "patagonia"] },
      { text: "🇧🇪", shortCode: ":flag_be:", value: "🇧🇪", searchKeywords: ["belgium", "brussels", "europe", "belgian", "waffles", "chocolate", "beer", "flemish"] },
      { text: "🇨🇭", shortCode: ":flag_ch:", value: "🇨🇭", searchKeywords: ["switzerland", "bern", "europe", "swiss", "alps", "chocolate", "cheese", "bank"] },
      { text: "🇵🇱", shortCode: ":flag_pl:", value: "🇵🇱", searchKeywords: ["poland", "warsaw", "europe", "polish", "pierogi", "vodka", "baltic", "wroclaw"] },
      { text: "🇵🇹", shortCode: ":flag_pt:", value: "🇵🇹", searchKeywords: ["portugal", "lisbon", "europe", "portuguese", "port", "azores", "madeira", "fado"] },
      { text: "🇮🇩", shortCode: ":flag_id:", value: "🇮🇩", searchKeywords: ["indonesia", "jakarta", "asia", "indonesian", "bali", "java", "sumatra", "komodo"] },
      { text: "🇳🇬", shortCode: ":flag_ng:", value: "🇳🇬", searchKeywords: ["nigeria", "lagos", "africa", "nigerian", "abuja", "nollywood", "afrobeats", "yoruba"] },
      { text: "🇳🇴", shortCode: ":flag_no:", value: "🇳🇴", searchKeywords: ["norway", "oslo", "europe", "norwegian", "nordic", "fjord", "vikings", "aurora"] },
      { text: "🇩🇰", shortCode: ":flag_dk:", value: "🇩🇰", searchKeywords: ["denmark", "copenhagen", "europe", "danish", "nordic", "lego", "viking", "hygge"] },
      { text: "🇫🇮", shortCode: ":flag_fi:", value: "🇫🇮", searchKeywords: ["finland", "helsinki", "europe", "finnish", "nordic", "sauna", "lapland", "santa"] },
      { text: "🇬🇷", shortCode: ":flag_gr:", value: "🇬🇷", searchKeywords: ["greece", "athens", "europe", "greek", "santorini", "mykonos", "parthenon", "olympics"] },
      { text: "🇭🇺", shortCode: ":flag_hu:", value: "🇭🇺", searchKeywords: ["hungary", "budapest", "europe", "hungarian", "goulash", "danube", "paprika", "balaton"] },
      { text: "🇮🇪", shortCode: ":flag_ie:", value: "🇮🇪", searchKeywords: ["ireland", "dublin", "europe", "irish", "shamrock", "guinness", "leprechaun", "celtic"] },
      { text: "🇱🇻", shortCode: ":flag_lv:", value: "🇱🇻", searchKeywords: ["latvia", "riga", "europe", "latvian", "baltic", "riga", "song festival", "amber"] },
      { text: "🇺🇦", shortCode: ":flag_ua:", value: "🇺🇦", searchKeywords: ["ukraine", "kyiv", "europe", "ukrainian", "kiev", "chernobyl", "borscht", "carpathian"] },
      { text: "🇻🇳", shortCode: ":flag_vn:", value: "🇻🇳", searchKeywords: ["vietnam", "hanoi", "asia", "vietnamese", "ho chi minh", "pho", "halong bay", "saigon"] },
      { text: "🇹🇭", shortCode: ":flag_th:", value: "🇹🇭", searchKeywords: ["thailand", "bangkok", "asia", "thai", "phuket", "pad thai", "temple", "beach"] },
      { text: "🇸🇬", shortCode: ":flag_sg:", value: "🇸🇬", searchKeywords: ["singapore", "asia", "singaporean", "lion city", "marina bay", "hawker", "sentosa", "merlion"] },
      { text: "🇲🇾", shortCode: ":flag_my:", value: "🇲🇾", searchKeywords: ["malaysia", "kuala lumpur", "asia", "malaysian", "penang", "langkawi", "petronas", "nasi lemak"] },
      { text: "🇵🇭", shortCode: ":flag_ph:", value: "🇵🇭", searchKeywords: ["philippines", "manila", "asia", "filipino", "cebu", "boracay", "adobo", "jeepney"] },
      { text: "🇨🇱", shortCode: ":flag_cl:", value: "🇨🇱", searchKeywords: ["chile", "santiago", "south america", "chilean", "patagonia", "easter island", "wine", "andes"] },
      { text: "🇵🇪", shortCode: ":flag_pe:", value: "🇵🇪", searchKeywords: ["peru", "lima", "south america", "peruvian", "machu picchu", "inca", "llama", "ceviche"] },
      { text: "🇨🇴", shortCode: ":flag_co:", value: "🇨🇴", searchKeywords: ["colombia", "south america", "bogota", "coffee", "latin"] },
      { text: "🇮🇱", shortCode: ":flag_il:", value: "🇮🇱", searchKeywords: ["israel", "middle east", "jerusalem", "jewish", "tel aviv"] },
      { text: "🇦🇪", shortCode: ":flag_ae:", value: "🇦🇪", searchKeywords: ["uae", "dubai", "arab emirates", "middle east", "abu dhabi"] },
      { text: "🇪🇺", shortCode: ":flag_eu:", value: "🇪🇺", searchKeywords: ["european union", "europe", "eu", "unity", "european"] },
      { text: "🇺🇳", shortCode: ":flag_un:", value: "🇺🇳", searchKeywords: ["united nations", "un", "global", "world", "international"] },
      { text: "🏴‍☠️", shortCode: ":pirate_flag:", value: "🏴‍☠️", searchKeywords: ["pirate", "skull", "crossbones", "jolly roger", "sea", "treasure"] },
      { text: "🏳️‍🌈", shortCode: ":rainbow_flag:", value: "🏳️‍🌈", searchKeywords: ["gay", "pride", "lgbt", "lgbtq", "rainbow", "homosexual", "queer", "pride month"] },
      { text: "🏴", shortCode: ":flag_white:", value: "🏴", searchKeywords: ["white", "surrender", "peace", "flag", "plain", "neutral"] },
      { text: "🏳️‍⚧️", shortCode: ":transgender_flag:", value: "🏳️‍⚧️", searchKeywords: ["transgender", "trans", "lgbt", "lgbtq", "pride", "gender", "identity"] },
      { text: "⚧️", shortCode: ":transgender_symbol:", value: "⚧️", searchKeywords: ["transgender", "trans", "symbol", "lgbt", "gender", "identity"] },
      { text: "🇯🇲", shortCode: ":flag_jm:", value: "🇯🇲", searchKeywords: ["jamaica", "caribbean", "island", "reggae", "bob marley", "west indies"] },
      { text: "🇨🇺", shortCode: ":flag_cu:", value: "🇨🇺", searchKeywords: ["cuba", "caribbean", "havana", "cigar", "island", "communist"] },
      { text: "🇵🇷", shortCode: ":flag_pr:", value: "🇵🇷", searchKeywords: ["puerto rico", "caribbean", "island", "san juan", "territory", "latin"] },
      { text: "🇩🇴", shortCode: ":flag_do:", value: "🇩🇴", searchKeywords: ["dominican republic", "caribbean", "island", "santo domingo", "latin"] },
      { text: "🇵🇦", shortCode: ":flag_pa:", value: "🇵🇦", searchKeywords: ["panama", "canal", "central america", "latin", "isthmus"] },
      { text: "🇨🇷", shortCode: ":flag_cr:", value: "🇨🇷", searchKeywords: ["costa rica", "central america", "san jose", "rainforest", "latin"] },
      { text: "🇬🇹", shortCode: ":flag_gt:", value: "🇬🇹", searchKeywords: ["guatemala", "central america", "maya", "latin", "guatemala city"] },
      { text: "🇸🇻", shortCode: ":flag_sv:", value: "🇸🇻", searchKeywords: ["el salvador", "central america", "san salvador", "latin", "pupusas"] },
      { text: "🇭🇳", shortCode: ":flag_hn:", value: "🇭🇳", searchKeywords: ["honduras", "central america", "tegucigalpa", "latin", "caribbean"] },
      { text: "🇳🇮", shortCode: ":flag_ni:", value: "🇳🇮", searchKeywords: ["nicaragua", "central america", "managua", "latin", "lake"] },
      { text: "🇧🇿", shortCode: ":flag_bz:", value: "🇧🇿", searchKeywords: ["belize", "central america", "caribbean", "barrier reef", "latin"] },
      { text: "🇦🇹", shortCode: ":flag_at:", value: "🇦🇹", searchKeywords: ["austria", "vienna", "europe", "alps", "german", "mozart"] },
      { text: "🇳🇿", shortCode: ":flag_nz:", value: "🇳🇿", searchKeywords: ["new zealand", "kiwi", "oceania", "wellington", "island", "maori"] },
      { text: "🇿🇦", shortCode: ":flag_za:", value: "🇿🇦", searchKeywords: ["south africa", "africa", "johannesburg", "cape town", "mandela", "rainbow nation"] },
    ],
  },
];

type EmojiItem = {
  text: string;
  shortCode: string;
  value: string;
  searchKeywords?: string[];
};

type EmojiCategory = {
  categoryText: string;
  value: string;
  emojis: EmojiItem[];
};

export type { EmojiItem, EmojiCategory };


export default emojiArray;
