const emojiArray = [
  {
    categoryText: "People",
    value: "people",
    emojis: [
      { text: "😀", shortCode: ":grinning:", value: "😀" },
      { text: "😃", shortCode: ":smiley:", value: "😃" },
      { text: "😄", shortCode: ":smile:", value: "😄" },
      { text: "😁", shortCode: ":grin:", value: "😁" },
      { text: "😂", shortCode: ":joy:", value: "😂" },
      { text: "🤣", shortCode: ":rofl:", value: "🤣" },
      { text: "🙂", shortCode: ":slightly_smiling_face:", value: "🙂" },
      { text: "😉", shortCode: ":wink:", value: "😉" },
      { text: "😊", shortCode: ":blush:", value: "😊" },
      { text: "😍", shortCode: ":heart_eyes:", value: "😍" },
      { text: "😘", shortCode: ":kissing_heart:", value: "😘" },
      { text: "😜", shortCode: ":stuck_out_tongue_winking_eye:", value: "😜" },
      { text: "😝", shortCode: ":stuck_out_tongue_closed_eyes:", value: "😝" },
      { text: "😒", shortCode: ":unamused:", value: "😒" },
      { text: "🤔", shortCode: ":thinking:", value: "🤔" },
      { text: "🙄", shortCode: ":roll_eyes:", value: "🙄" },
      { text: "😭", shortCode: ":sob:", value: "😭" },
      { text: "😩", shortCode: ":weary:", value: "😩" },
      { text: "😡", shortCode: ":rage:", value: "😡" },
      { text: "👍", shortCode: ":thumbsup:", value: "👍" },
      { text: "👎", shortCode: ":thumbsdown:", value: "👎" },
      { text: "🙌", shortCode: ":raised_hands:", value: "🙌" },
      { text: "🙏", shortCode: ":pray:", value: "🙏" },
      { text: "👏", shortCode: ":clap:", value: "👏" },
      { text: "🤷‍♂️", shortCode: ":man_shrugging:", value: "🤷‍♂️" },
      { text: "🤦‍♀️", shortCode: ":woman_facepalming:", value: "🤦‍♀️" },
      { text: "🤞", shortCode: ":crossed_fingers:", value: "🤞" },
      { text: "💯", shortCode: ":100:", value: "💯" },
    ],
  },
  {
    categoryText: "Nature",
    value: "nature",
    emojis: [
      { text: "🐶", shortCode: ":dog:", value: "🐶" },
      { text: "🐱", shortCode: ":cat:", value: "🐱" },
      { text: "🐭", shortCode: ":mouse:", value: "🐭" },
      { text: "🐹", shortCode: ":hamster:", value: "🐹" },
      { text: "🐰", shortCode: ":rabbit:", value: "🐰" },
      { text: "🦊", shortCode: ":fox_face:", value: "🦊" },
      { text: "🐻", shortCode: ":bear:", value: "🐻" },
      { text: "🐼", shortCode: ":panda_face:", value: "🐼" },
      { text: "🐨", shortCode: ":koala:", value: "🐨" },
      { text: "🐯", shortCode: ":tiger:", value: "🐯" },
      { text: "🐮", shortCode: ":cow:", value: "🐮" },
      { text: "🐷", shortCode: ":pig:", value: "🐷" },
      { text: "🐸", shortCode: ":frog:", value: "🐸" },
      { text: "🐵", shortCode: ":monkey_face:", value: "🐵" },
      { text: "🐔", shortCode: ":chicken:", value: "🐔" },
      { text: "🐧", shortCode: ":penguin:", value: "🐧" },
      { text: "🐦", shortCode: ":bird:", value: "🐦" },
      { text: "🐝", shortCode: ":bee:", value: "🐝" },
      { text: "🐛", shortCode: ":bug:", value: "🐛" },
      { text: "🦋", shortCode: ":butterfly:", value: "🦋" },
      { text: "🌸", shortCode: ":cherry_blossom:", value: "🌸" },
      { text: "🌼", shortCode: ":blossom:", value: "🌼" },
      { text: "🌻", shortCode: ":sunflower:", value: "🌻" },
      { text: "🌺", shortCode: ":hibiscus:", value: "🌺" },
      { text: "🌱", shortCode: ":seedling:", value: "🌱" },
      { text: "🌲", shortCode: ":evergreen_tree:", value: "🌲" },
      { text: "☀️", shortCode: ":sunny:", value: "☀️" },
      { text: "🌧️", shortCode: ":cloud_with_rain:", value: "🌧️" },
    ],
  },
  {
    categoryText: "Food",
    value: "food",
    emojis: [
      { text: "🍏", shortCode: ":green_apple:", value: "🍏" },
      { text: "🍎", shortCode: ":apple:", value: "🍎" },
      { text: "🍐", shortCode: ":pear:", value: "🍐" },
      { text: "🍊", shortCode: ":tangerine:", value: "🍊" },
      { text: "🍋", shortCode: ":lemon:", value: "🍋" },
      { text: "🍌", shortCode: ":banana:", value: "🍌" },
      { text: "🍉", shortCode: ":watermelon:", value: "🍉" },
      { text: "🍇", shortCode: ":grapes:", value: "🍇" },
      { text: "🍓", shortCode: ":strawberry:", value: "🍓" },
      { text: "🍒", shortCode: ":cherries:", value: "🍒" },
      { text: "🍑", shortCode: ":peach:", value: "🍑" },
      { text: "🍍", shortCode: ":pineapple:", value: "🍍" },
      { text: "🥭", shortCode: ":mango:", value: "🥭" },
      { text: "🍅", shortCode: ":tomato:", value: "🍅" },
      { text: "🍆", shortCode: ":eggplant:", value: "🍆" },
      { text: "🥑", shortCode: ":avocado:", value: "🥑" },
      { text: "🥦", shortCode: ":broccoli:", value: "🥦" },
      { text: "🥕", shortCode: ":carrot:", value: "🥕" },
      { text: "🌽", shortCode: ":corn:", value: "🌽" },
      { text: "🌶️", shortCode: ":hot_pepper:", value: "🌶️" },
      { text: "🥐", shortCode: ":croissant:", value: "🥐" },
      { text: "🍞", shortCode: ":bread:", value: "🍞" },
      { text: "🧀", shortCode: ":cheese:", value: "🧀" },
      { text: "🍗", shortCode: ":poultry_leg:", value: "🍗" },
      { text: "🍖", shortCode: ":meat_on_bone:", value: "🍖" },
      { text: "🍔", shortCode: ":hamburger:", value: "🍔" },
      { text: "🍟", shortCode: ":fries:", value: "🍟" },
      { text: "🍕", shortCode: ":pizza:", value: "🍕" },
      { text: "🍣", shortCode: ":sushi:", value: "🍣" },
      { text: "☕️", shortCode: ":coffee:", value: "☕️" },
      { text: "🍺", shortCode: ":beer:", value: "🍺" },
      { text: "🍷", shortCode: ":wine_glass:", value: "🍷" },
      { text: "🥤", shortCode: ":cup_with_straw:", value: "🥤" },
    ],
  },
  {
    categoryText: "Activities",
    value: "activities",
    emojis: [
      { text: "⚽️", shortCode: ":soccer:", value: "⚽️" },
      { text: "🏀", shortCode: ":basketball:", value: "🏀" },
      { text: "🏈", shortCode: ":football:", value: "🏈" },
      { text: "⚾️", shortCode: ":baseball:", value: "⚾️" },
      { text: "🎾", shortCode: ":tennis:", value: "🎾" },
      { text: "🏐", shortCode: ":volleyball:", value: "🏐" },
      { text: "🏉", shortCode: ":rugby_football:", value: "🏉" },
      { text: "🎱", shortCode: ":8ball:", value: "🎱" },
      { text: "🏓", shortCode: ":ping_pong:", value: "🏓" },
      { text: "🏸", shortCode: ":badminton:", value: "🏸" },
      { text: "🥊", shortCode: ":boxing_glove:", value: "🥊" },
      { text: "🥋", shortCode: ":martial_arts_uniform:", value: "🥋" },
      { text: "⛳️", shortCode: ":golf:", value: "⛳️" },
      { text: "🏹", shortCode: ":bow_and_arrow:", value: "🏹" },
      { text: "🎣", shortCode: ":fishing_pole_and_fish:", value: "🎣" },
      { text: "🏆", shortCode: ":trophy:", value: "🏆" },
      { text: "🎮", shortCode: ":video_game:", value: "🎮" },
      { text: "🎲", shortCode: ":game_die:", value: "🎲" },
      { text: "🎯", shortCode: ":dart:", value: "🎯" },
      { text: "🎬", shortCode: ":clapper:", value: "🎬" },
      { text: "🎤", shortCode: ":microphone:", value: "🎤" },
      { text: "🎧", shortCode: ":headphones:", value: "🎧" },
      { text: "🎸", shortCode: ":guitar:", value: "🎸" },
      { text: "🎹", shortCode: ":musical_keyboard:", value: "🎹" },
      { text: "🎭", shortCode: ":performing_arts:", value: "🎭" },
    ],
  },
  {
    categoryText: "travel",
    value: "travel",
    emojis: [
      { text: "🚗", shortCode: ":car:", value: "🚗" },
      { text: "🚕", shortCode: ":taxi:", value: "🚕" },
      { text: "🚙", shortCode: ":blue_car:", value: "🚙" },
      { text: "🚌", shortCode: ":bus:", value: "🚌" },
      { text: "🚎", shortCode: ":trolleybus:", value: "🚎" },
      { text: "🚓", shortCode: ":police_car:", value: "🚓" },
      { text: "🚑", shortCode: ":ambulance:", value: "🚑" },
      { text: "🚒", shortCode: ":fire_engine:", value: "🚒" },
      { text: "🚐", shortCode: ":minibus:", value: "🚐" },
      { text: "🚚", shortCode: ":truck:", value: "🚚" },
      { text: "🚛", shortCode: ":articulated_lorry:", value: "🚛" },
      { text: "🚜", shortCode: ":tractor:", value: "🚜" },
      { text: "🚲", shortCode: ":bicycle:", value: "🚲" },
      { text: "🛴", shortCode: ":scooter:", value: "🛴" },
      { text: "🏍️", shortCode: ":motorcycle:", value: "🏍️" },
      { text: "🛵", shortCode: ":motor_scooter:", value: "🛵" },
      { text: "🚢", shortCode: ":ship:", value: "🚢" },
      { text: "✈️", shortCode: ":airplane:", value: "✈️" },
      { text: "🛩️", shortCode: ":small_airplane:", value: "🛩️" },
      { text: "🚀", shortCode: ":rocket:", value: "🚀" },
      { text: "🗺️", shortCode: ":world_map:", value: "🗺️" },
      { text: "🗽", shortCode: ":statue_of_liberty:", value: "🗽" },
      { text: "🗼", shortCode: ":tokyo_tower:", value: "🗼" },
      { text: "🏝️", shortCode: ":island:", value: "🏝️" },
      { text: "🏖️", shortCode: ":beach_with_umbrella:", value: "🏖️" },
    ],
  },
  {
    categoryText: "Objects",
    value: "objects",
    emojis: [
      { text: "🔑", shortCode: ":key:", value: "🔑" },
      { text: "🧭", shortCode: ":compass:", value: "🧭" },
      { text: "🧰", shortCode: ":toolbox:", value: "🧰" },
      { text: "🛠️", shortCode: ":hammer_and_wrench:", value: "🛠️" },
      { text: "🔨", shortCode: ":hammer:", value: "🔨" },
      { text: "🔧", shortCode: ":wrench:", value: "🔧" },
      { text: "🔩", shortCode: ":nut_and_bolt:", value: "🔩" },
      { text: "⚙️", shortCode: ":gear:", value: "⚙️" },
      { text: "💡", shortCode: ":bulb:", value: "💡" },
      { text: "🔦", shortCode: ":flashlight:", value: "🔦" },
      { text: "🧯", shortCode: ":fire_extinguisher:", value: "🧯" },
      { text: "🧪", shortCode: ":test_tube:", value: "🧪" },
      { text: "🔬", shortCode: ":microscope:", value: "🔬" },
      { text: "🧬", shortCode: ":dna:", value: "🧬" },
      { text: "🖥️", shortCode: ":desktop_computer:", value: "🖥️" },
      { text: "💻", shortCode: ":laptop:", value: "💻" },
      { text: "🖨️", shortCode: ":printer:", value: "🖨️" },
      { text: "🖱️", shortCode: ":computer_mouse:", value: "🖱️" },
      { text: "📱", shortCode: ":iphone:", value: "📱" },
      { text: "📷", shortCode: ":camera:", value: "📷" },
      { text: "🎥", shortCode: ":movie_camera:", value: "🎥" },
      { text: "📺", shortCode: ":tv:", value: "📺" },
      { text: "📦", shortCode: ":package:", value: "📦" },
      { text: "⏰", shortCode: ":alarm_clock:", value: "⏰" },
    ],
  },
  {
    categoryText: "Symbols",
    value: "symbols",
    emojis: [
      { text: "❤️", shortCode: ":heart:", value: "❤️" },
      { text: "💛", shortCode: ":yellow_heart:", value: "💛" },
      { text: "💚", shortCode: ":green_heart:", value: "💚" },
      { text: "💙", shortCode: ":blue_heart:", value: "💙" },
      { text: "💜", shortCode: ":purple_heart:", value: "💜" },
      { text: "🖤", shortCode: ":black_heart:", value: "🖤" },
      { text: "💔", shortCode: ":broken_heart:", value: "💔" },
      { text: "🔥", shortCode: ":fire:", value: "🔥" },
      { text: "⭐️", shortCode: ":star:", value: "⭐️" },
      { text: "✨", shortCode: ":sparkles:", value: "✨" },
      { text: "⚡️", shortCode: ":zap:", value: "⚡️" },
      { text: "⭕️", shortCode: ":o:", value: "⭕️" },
      { text: "✅", shortCode: ":white_check_mark:", value: "✅" },
      { text: "❌", shortCode: ":x:", value: "❌" },
      { text: "➕", shortCode: ":heavy_plus_sign:", value: "➕" },
      { text: "➖", shortCode: ":heavy_minus_sign:", value: "➖" },
      { text: "♻️", shortCode: ":recycle:", value: "♻️" },
      { text: "💯", shortCode: ":100:", value: "💯" },
      { text: "🔁", shortCode: ":repeat:", value: "🔁" },
      { text: "🔃", shortCode: ":repeat_one:", value: "🔃" },
      { text: "♈️", shortCode: ":aries:", value: "♈️" },
      { text: "♉️", shortCode: ":taurus:", value: "♉️" },
      { text: "♊️", shortCode: ":gemini:", value: "♊️" },
      { text: "♋️", shortCode: ":cancer:", value: "♋️" },
      { text: "♌️", shortCode: ":leo:", value: "♌️" },
      { text: "♍️", shortCode: ":virgo:", value: "♍️" },
    ],
  },
  {
    categoryText: "Flags",
    value: "flags",
    emojis: [
      { text: "🇺🇸", shortCode: ":flag_us:", value: "🇺🇸" },
      { text: "🇬🇧", shortCode: ":flag_gb:", value: "🇬🇧" },
      { text: "🇨🇦", shortCode: ":flag_ca:", value: "🇨🇦" },
      { text: "🇩🇪", shortCode: ":flag_de:", value: "🇩🇪" },
      { text: "🇫🇷", shortCode: ":flag_fr:", value: "🇫🇷" },
      { text: "🇪🇸", shortCode: ":flag_es:", value: "🇪🇸" },
      { text: "🇮🇹", shortCode: ":flag_it:", value: "🇮🇹" },
      { text: "🇯🇵", shortCode: ":flag_jp:", value: "🇯🇵" },
      { text: "🇰🇷", shortCode: ":flag_kr:", value: "🇰🇷" },
      { text: "🇨🇳", shortCode: ":flag_cn:", value: "🇨🇳" },
      { text: "🇮🇳", shortCode: ":flag_in:", value: "🇮🇳" },
      { text: "🇧🇷", shortCode: ":flag_br:", value: "🇧🇷" },
      { text: "🇲🇽", shortCode: ":flag_mx:", value: "🇲🇽" },
      { text: "🇦🇺", shortCode: ":flag_au:", value: "🇦🇺" },
      { text: "🇳🇱", shortCode: ":flag_nl:", value: "🇳🇱" },
      { text: "🇸🇪", shortCode: ":flag_se:", value: "🇸🇪" },
      { text: "🇷🇺", shortCode: ":flag_ru:", value: "🇷🇺" },
      { text: "🇹🇷", shortCode: ":flag_tr:", value: "🇹🇷" },
      { text: "🇸🇦", shortCode: ":flag_sa:", value: "🇸🇦" },
      { text: "🇿🇦", shortCode: ":flag_za:", value: "🇿🇦" },
      { text: "🇦🇷", shortCode: ":flag_ar:", value: "🇦🇷" },
      { text: "🇧🇪", shortCode: ":flag_be:", value: "🇧🇪" },
      { text: "🇨🇭", shortCode: ":flag_ch:", value: "🇨🇭" },
      { text: "🇵🇱", shortCode: ":flag_pl:", value: "🇵🇱" },
      { text: "🇵🇹", shortCode: ":flag_pt:", value: "🇵🇹" },
      { text: "🇮🇩", shortCode: ":flag_id:", value: "🇮🇩" },
      { text: "🇳🇬", shortCode: ":flag_ng:", value: "🇳🇬" },
      { text: "🇳🇴", shortCode: ":flag_no:", value: "🇳🇴" },
      { text: "🇩🇰", shortCode: ":flag_dk:", value: "🇩🇰" },
    ],
  },
];

type EmojiItem = {
  text: string;
  shortCode: string;
  value: string;
};

type EmojiCategory = {
  categoryText: string;
  value: string;
  emojis: EmojiItem[];
};

export type { EmojiItem, EmojiCategory };


export default emojiArray;
