const emojiArray = [
  {
    name: "People",
    value: "people",
    emojis: [
      { unicode: "\\u{1F600}", emoji: "😀", shortcode: ":smile:" },
      { unicode: "\\u{1F603}", emoji: "😃", shortcode: ":smiley:" },
      { unicode: "\\u{1F604}", emoji: "😄", shortcode: ":grin:" },
      { unicode: "\\u{1F601}", emoji: "😁", shortcode: ":beaming:" },
      { unicode: "\\u{1F606}", emoji: "😆", shortcode: ":laugh:" },
      { unicode: "\\u{1F605}", emoji: "😅", shortcode: ":sweat:" },
      { unicode: "\\u{1F602}", emoji: "😂", shortcode: ":joy:" },
      { unicode: "\\u{1F923}", emoji: "🤣", shortcode: ":rofl:" },
      { unicode: "\\u{1F642}", emoji: "🙂", shortcode: ":slight:" },
      { unicode: "\\u{1F643}", emoji: "🙃", shortcode: ":upsidedown:" },
      { unicode: "\\u{1F609}", emoji: "😉", shortcode: ":wink:" },
      { unicode: "\\u{1F60A}", emoji: "😊", shortcode: ":blush:" },
      { unicode: "\\u{1F607}", emoji: "😇", shortcode: ":angel:" },
      { unicode: "\\u{1F970}", emoji: "🥰", shortcode: ":heart_eyes:" },
      { unicode: "\\u{1F60D}", emoji: "😍", shortcode: ":love:" },
      { unicode: "\\u{1F929}", emoji: "🤩", shortcode: ":star:" },
      { unicode: "\\u{1F618}", emoji: "😘", shortcode: ":kiss:" },
      { unicode: "\\u{1F617}", emoji: "😗", shortcode: ":kissing:" },
      { unicode: "\\u{1F61A}", emoji: "😚", shortcode: ":kissingc:" },
      { unicode: "\\u{1F619}", emoji: "😙", shortcode: ":kissing_sm:" },
      { unicode: "\\u{1F972}", emoji: "🥲", shortcode: ":smilecry:" },
      { unicode: "\\u{1F60B}", emoji: "😋", shortcode: ":yum:" },
      { unicode: "\\u{1F61B}", emoji: "😛", shortcode: ":tongue:" },
      { unicode: "\\u{1F61C}", emoji: "😜", shortcode: ":winky:" },
      { unicode: "\\u{1F92A}", emoji: "🤪", shortcode: ":zany:" },
      { unicode: "\\u{1F60C}", emoji: "😌", shortcode: ":relieved:" },
      { unicode: "\\u{1F614}", emoji: "😔", shortcode: ":pensive:" },
      { unicode: "\\u{1F611}", emoji: "😑", shortcode: ":blank:" },
      { unicode: "\\u{1F610}", emoji: "😐", shortcode: ":neutral:" },
      { unicode: "\\u{1F60F}", emoji: "😏", shortcode: ":smirk:" },
      { unicode: "\\u{1F612}", emoji: "😒", shortcode: ":unamused:" },
      { unicode: "\\u{1F644}", emoji: "🙄", shortcode: ":roll_eyes:" },
      { unicode: "\\u{1F62C}", emoji: "😬", shortcode: ":grimace:" },
      { unicode: "\\u{1F925}", emoji: "🤥", shortcode: ":lying:" },
      { unicode: "\\u{1F62B}", emoji: "😫", shortcode: ":tired:" },
      { unicode: "\\u{1F62A}", emoji: "😪", shortcode: ":sleepy:" },
      { unicode: "\\u{1F924}", emoji: "🤤", shortcode: ":drool:" },
      { unicode: "\\u{1F637}", emoji: "😷", shortcode: ":mask:" },
      { unicode: "\\u{1F912}", emoji: "🤒", shortcode: ":sick:" },
      { unicode: "\\u{1F915}", emoji: "🤕", shortcode: ":injured:" },
      { unicode: "\\u{1F922}", emoji: "🤢", shortcode: ":nausea:" },
      { unicode: "\\u{1F92E}", emoji: "🤮", shortcode: ":vomit:" },
      { unicode: "\\u{1F927}", emoji: "🤧", shortcode: ":sneeze:" },
      { unicode: "\\u{1F928}", emoji: "🤨", shortcode: ":raisedbrow:" },
      { unicode: "\\u{1F630}", emoji: "😰", shortcode: ":anxious:" },
      { unicode: "\\u{1F622}", emoji: "😢", shortcode: ":cry:" },
      { unicode: "\\u{1F62D}", emoji: "😭", shortcode: ":sob:" },
      { unicode: "\\u{1F631}", emoji: "😱", shortcode: ":scream:" },
      { unicode: "\\u{1F973}", emoji: "🥳", shortcode: ":party:" },
      { unicode: "\\u{1F92F}", emoji: "🤯", shortcode: ":mindblown:" },
    ],
  },
  {
    name: "Nature",
    value: "nature",
    emojis: [
      { unicode: "\\u{1F436}", emoji: "🐶", shortcode: ":dog:" },
      { unicode: "\\u{1F431}", emoji: "🐱", shortcode: ":cat:" },
      { unicode: "\\u{1F42D}", emoji: "🐭", shortcode: ":mouse:" },
      { unicode: "\\u{1F439}", emoji: "🐹", shortcode: ":hamster:" },
      { unicode: "\\u{1F430}", emoji: "🐰", shortcode: ":rabbit:" },
      { unicode: "\\u{1F98A}", emoji: "🦊", shortcode: ":fox:" },
      { unicode: "\\u{1F43B}", emoji: "🐻", shortcode: ":bear:" },
      { unicode: "\\u{1F43C}", emoji: "🐼", shortcode: ":panda:" },
      { unicode: "\\u{1F428}", emoji: "🐨", shortcode: ":koala:" },
      { unicode: "\\u{1F42F}", emoji: "🐯", shortcode: ":tiger:" },
      { unicode: "\\u{1F981}", emoji: "🦁", shortcode: ":lion:" },
      { unicode: "\\u{1F42E}", emoji: "🐮", shortcode: ":cow:" },
      { unicode: "\\u{1F437}", emoji: "🐷", shortcode: ":pig:" },
      { unicode: "\\u{1F438}", emoji: "🐸", shortcode: ":frog:" },
      { unicode: "\\u{1F435}", emoji: "🐵", shortcode: ":monkey:" },
      { unicode: "\\u{1F648}", emoji: "🙈", shortcode: ":see_no_evil:" },
      { unicode: "\\u{1F649}", emoji: "🙉", shortcode: ":hear_no_evil:" },
      { unicode: "\\u{1F64A}", emoji: "🙊", shortcode: ":speak_no_evil:" },
      { unicode: "\\u{1F414}", emoji: "🐔", shortcode: ":chicken:" },
      { unicode: "\\u{1F427}", emoji: "🐧", shortcode: ":penguin:" },
      { unicode: "\\u{1F426}", emoji: "🐦", shortcode: ":bird:" },
      { unicode: "\\u{1F424}", emoji: "🐤", shortcode: ":chick:" },
      { unicode: "\\u{1F426}", emoji: "🐦", shortcode: ":bird2:" },
      { unicode: "\\u{1F986}", emoji: "🦆", shortcode: ":duck:" },
      { unicode: "\\u{1F985}", emoji: "🦅", shortcode: ":eagle:" },
      { unicode: "\\u{1F989}", emoji: "🦉", shortcode: ":owl:" },
      { unicode: "\\u{1F987}", emoji: "🦇", shortcode: ":bat:" },
      { unicode: "\\u{1F43A}", emoji: "🐺", shortcode: ":wolf:" },
      { unicode: "\\u{1F417}", emoji: "🐗", shortcode: ":boar:" },
      { unicode: "\\u{1F434}", emoji: "🐴", shortcode: ":horse:" },
      { unicode: "\\u{1F984}", emoji: "🦄", shortcode: ":unicorn:" },
      { unicode: "\\u{1F41D}", emoji: "🐝", shortcode: ":bee:" },
      { unicode: "\\u{1F41B}", emoji: "🐛", shortcode: ":bug:" },
      { unicode: "\\u{1F98B}", emoji: "🦋", shortcode: ":butterfly:" },
      { unicode: "\\u{1F40C}", emoji: "🐌", shortcode: ":snail:" },
      { unicode: "\\u{1F41E}", emoji: "🐞", shortcode: ":ladybird:" },
      { unicode: "\\u{1F41C}", emoji: "🐜", shortcode: ":ant:" },
      { unicode: "\\u{1FAB0}", emoji: "🪰", shortcode: ":fly2:" },
      { unicode: "\\u{1F422}", emoji: "🐢", shortcode: ":turtle:" },
      { unicode: "\\u{1F40D}", emoji: "🐍", shortcode: ":snake:" },
      { unicode: "\\u{1F419}", emoji: "🐙", shortcode: ":octopus:" },
      { unicode: "\\u{1F991}", emoji: "🦑", shortcode: ":squid:" },
      { unicode: "\\u{1F990}", emoji: "🦐", shortcode: ":shrimp:" },
      { unicode: "\\u{1F99E}", emoji: "🦞", shortcode: ":lobster:" },
      { unicode: "\\u{1F980}", emoji: "🦀", shortcode: ":crab:" },
      { unicode: "\\u{1F421}", emoji: "🐡", shortcode: ":blowfish:" },
      { unicode: "\\u{1F420}", emoji: "🐠", shortcode: ":tropical:" },
      { unicode: "\\u{1F41F}", emoji: "🐟", shortcode: ":fish:" },
      { unicode: "\\u{1F42C}", emoji: "🐬", shortcode: ":dolphin:" },
      { unicode: "\\u{1F433}", emoji: "🐳", shortcode: ":whale:" },
      { unicode: "\\u{1F40B}", emoji: "🐋", shortcode: ":whale2:" },
      { unicode: "\\u{1F338}", emoji: "🌸", shortcode: ":blossom:" },
      { unicode: "\\u{1F33C}", emoji: "🌼", shortcode: ":flower:" },
    ],
  },
  {
    name: "Food",
    value: "food",
    emojis: [
      { unicode: "\\u{1F34F}", emoji: "🍏", shortcode: ":greenapp:" },
      { unicode: "\\u{1F34E}", emoji: "🍎", shortcode: ":apple:" },
      { unicode: "\\u{1F350}", emoji: "🍐", shortcode: ":pear:" },
      { unicode: "\\u{1F34A}", emoji: "🍊", shortcode: ":orange:" },
      { unicode: "\\u{1F34B}", emoji: "🍋", shortcode: ":lemon:" },
      { unicode: "\\u{1F34C}", emoji: "🍌", shortcode: ":banana:" },
      { unicode: "\\u{1F349}", emoji: "🍉", shortcode: ":melon:" },
      { unicode: "\\u{1F347}", emoji: "🍇", shortcode: ":grapes:" },
      { unicode: "\\u{1F353}", emoji: "🍓", shortcode: ":berry:" },
      { unicode: "\\u{1F348}", emoji: "🍈", shortcode: ":melon2:" },
      { unicode: "\\u{1F352}", emoji: "🍒", shortcode: ":cherry:" },
      { unicode: "\\u{1F351}", emoji: "🍑", shortcode: ":peach:" },
      { unicode: "\\u{1F96D}", emoji: "🥭", shortcode: ":mango:" },
      { unicode: "\\u{1F965}", emoji: "🥥", shortcode: ":coconut:" },
      { unicode: "\\u{1F951}", emoji: "🥑", shortcode: ":avocado:" },
      { unicode: "\\u{1F345}", emoji: "🍅", shortcode: ":tomato:" },
      { unicode: "\\u{1F346}", emoji: "🍆", shortcode: ":eggplant:" },
      { unicode: "\\u{1F966}", emoji: "🥦", shortcode: ":broccoli:" },
      { unicode: "\\u{1F96C}", emoji: "🥬", shortcode: ":greens:" },
      { unicode: "\\u{1F952}", emoji: "🥒", shortcode: ":cucumber:" },
      { unicode: "\\u{1F336}", emoji: "🌶️", shortcode: ":chili:" },
      { unicode: "\\u{1F33D}", emoji: "🌽", shortcode: ":corn:" },
      { unicode: "\\u{1F954}", emoji: "🥔", shortcode: ":potato:" },
      { unicode: "\\u{1F360}", emoji: "🍠", shortcode: ":yam:" },
      { unicode: "\\u{1F950}", emoji: "🥐", shortcode: ":croissant:" },
      { unicode: "\\u{1F35E}", emoji: "🍞", shortcode: ":bread:" },
      { unicode: "\\u{1F96F}", emoji: "🥯", shortcode: ":bagel:" },
      { unicode: "\\u{1F956}", emoji: "🥖", shortcode: ":baguette:" },
      { unicode: "\\u{1F968}", emoji: "🥨", shortcode: ":pretzel:" },
      { unicode: "\\u{1F9C0}", emoji: "🧀", shortcode: ":cheese:" },
      { unicode: "\\u{1F95A}", emoji: "🥚", shortcode: ":egg2:" },
      { unicode: "\\u{1F373}", emoji: "🍳", shortcode: ":cooking:" },
      { unicode: "\\u{1F9C8}", emoji: "🧈", shortcode: ":butter:" },
      { unicode: "\\u{1F95E}", emoji: "🥞", shortcode: ":pancake:" },
      { unicode: "\\u{1F953}", emoji: "🥓", shortcode: ":bacon:" },
      { unicode: "\\u{1F969}", emoji: "🥩", shortcode: ":steak:" },
      { unicode: "\\u{1F357}", emoji: "🍗", shortcode: ":drumstick:" },
      { unicode: "\\u{1F356}", emoji: "🍖", shortcode: ":meat:" },
      { unicode: "\\u{1F32D}", emoji: "🌭", shortcode: ":hotdog:" },
      { unicode: "\\u{1F354}", emoji: "🍔", shortcode: ":burger:" },
      { unicode: "\\u{1F35F}", emoji: "🍟", shortcode: ":fries2:" },
      { unicode: "\\u{1F355}", emoji: "🍕", shortcode: ":pizza:" },
      { unicode: "\\u{1F96A}", emoji: "🥪", shortcode: ":sandwich:" },
      { unicode: "\\u{1F959}", emoji: "🥙", shortcode: ":wrap:" },
      { unicode: "\\u{1F9C6}", emoji: "🧆", shortcode: ":falafel:" },
      { unicode: "\\u{1F32E}", emoji: "🌮", shortcode: ":taco:" },
      { unicode: "\\u{1F32F}", emoji: "🌯", shortcode: ":burrito:" },
      { unicode: "\\u{1F957}", emoji: "🥗", shortcode: ":salad:" },
      { unicode: "\\u{1F958}", emoji: "🥘", shortcode: ":paella:" },
      { unicode: "\\u{1F35D}", emoji: "🍝", shortcode: ":spag:" },
      { unicode: "\\u{1F35C}", emoji: "🍜", shortcode: ":ramen:" },
      { unicode: "\\u{1F372}", emoji: "🍲", shortcode: ":stew:" },
      { unicode: "\\u{1F35B}", emoji: "🍛", shortcode: ":curry:" },
      { unicode: "\\u{1F363}", emoji: "🍣", shortcode: ":sushi:" },
      { unicode: "\\u{1F371}", emoji: "🍱", shortcode: ":bento:" },
      { unicode: "\\u{1F95F}", emoji: "🥟", shortcode: ":dumpling:" },
    ],
  },
  {
    name: "Activities",
    value: "activities",
    emojis: [
      { unicode: "\\u{26BD}", emoji: "⚽", shortcode: ":soccer:" },
      { unicode: "\\u{1F3C0}", emoji: "🏀", shortcode: ":basket:" },
      { unicode: "\\u{1F3C8}", emoji: "🏈", shortcode: ":football:" },
      { unicode: "\\u{26BE}", emoji: "⚾", shortcode: ":baseball:" },
      { unicode: "\\u{1F94E}", emoji: "🥎", shortcode: ":softball:" },
      { unicode: "\\u{1F3BE}", emoji: "🎾", shortcode: ":tennis:" },
      { unicode: "\\u{1F3D0}", emoji: "🏐", shortcode: ":volley:" },
      { unicode: "\\u{1F3C9}", emoji: "🏉", shortcode: ":rugby:" },
      { unicode: "\\u{1F3CF}", emoji: "🥏", shortcode: ":disc:" },
      { unicode: "\\u{1F3B3}", emoji: "🎳", shortcode: ":bowling:" },
      { unicode: "\\u{1F3D3}", emoji: "🏓", shortcode: ":pingpong:" },
      { unicode: "\\u{1F3F8}", emoji: "🏸", shortcode: ":badmint:" },
      { unicode: "\\u{1F3D2}", emoji: "🏒", shortcode: ":hockey:" },
      { unicode: "\\u{1F3D1}", emoji: "🏑", shortcode: ":fieldhk:" },
      { unicode: "\\u{1F94D}", emoji: "🥍", shortcode: ":lacrosse:" },
      { unicode: "\\u{1F3A3}", emoji: "🎣", shortcode: ":fishng:" },
      { unicode: "\\u{1F3BD}", emoji: "🎽", shortcode: ":running:" },
      { unicode: "\\u{1F3BF}", emoji: "🎿", shortcode: ":skis:" },
      { unicode: "\\u{26F7}", emoji: "⛷️", shortcode: ":skier:" },
      { unicode: "\\u{1F3C2}", emoji: "🛷", shortcode: ":sled:" },
      { unicode: "\\u{1F3AF}", emoji: "🎯", shortcode: ":dart:" },
      { unicode: "\\u{1F3B2}", emoji: "🎲", shortcode: ":dice:" },
      { unicode: "\\u{2660}", emoji: "♠️", shortcode: ":spade:" },
      { unicode: "\\u{2665}", emoji: "♥️", shortcode: ":heart_suit:" },
      { unicode: "\\u{2666}", emoji: "♦️", shortcode: ":diamond:" },
      { unicode: "\\u{2663}", emoji: "♣️", shortcode: ":club:" },
      { unicode: "\\u{1F3AD}", emoji: "🎭", shortcode: ":theatre:" },
      { unicode: "\\u{1F3A8}", emoji: "🎨", shortcode: ":art:" },
      { unicode: "\\u{1F3AC}", emoji: "🎬", shortcode: ":movie:" },
      { unicode: "\\u{1F3A4}", emoji: "🎤", shortcode: ":sing:" },
      { unicode: "\\u{1F3A7}", emoji: "🎧", shortcode: ":dj:" },
      { unicode: "\\u{1F3BC}", emoji: "🎼", shortcode: ":score:" },
      { unicode: "\\u{1F3B9}", emoji: "🎹", shortcode: ":piano:" },
      { unicode: "\\u{1F941}", emoji: "🥁", shortcode: ":drum:" },
      { unicode: "\\u{1F3B7}", emoji: "🎷", shortcode: ":sax:" },
      { unicode: "\\u{1F3BA}", emoji: "🎺", shortcode: ":trumpet:" },
      { unicode: "\\u{1F3B8}", emoji: "🎸", shortcode: ":guitar2:" },
      { unicode: "\\u{1F942}", emoji: "🥂", shortcode: ":cheers:" },
      { unicode: "\\u{1F389}", emoji: "🎉", shortcode: ":tada:" },
      { unicode: "\\u{1F38A}", emoji: "🎊", shortcode: ":confeti:" },
      { unicode: "\\u{1F388}", emoji: "🎈", shortcode: ":balloon2:" },
      { unicode: "\\u{1F380}", emoji: "🎀", shortcode: ":ribbon2:" },
      { unicode: "\\u{1F381}", emoji: "🎁", shortcode: ":gift:" },
      { unicode: "\\u{1F3C6}", emoji: "🏆", shortcode: ":trophy2:" },
      { unicode: "\\u{1F3C5}", emoji: "🏅", shortcode: ":medal2:" },
      { unicode: "\\u{1F947}", emoji: "🥇", shortcode: ":gold:" },
      { unicode: "\\u{1F948}", emoji: "🥈", shortcode: ":silver:" },
      { unicode: "\\u{1F949}", emoji: "🥉", shortcode: ":bronze:" },
    ],
  },
  {
    name: "Travel",
    value: "travel",
    emojis: [
      { unicode: "\\u{1F697}", emoji: "🚗", shortcode: ":car2:" },
      { unicode: "\\u{1F695}", emoji: "🚕", shortcode: ":taxi2:" },
      { unicode: "\\u{1F699}", emoji: "🚙", shortcode: ":suv:" },
      { unicode: "\\u{1F68C}", emoji: "🚌", shortcode: ":bus2:" },
      { unicode: "\\u{1F68E}", emoji: "🚎", shortcode: ":trolley:" },
      { unicode: "\\u{1F3CE}", emoji: "🏎️", shortcode: ":race:" },
      { unicode: "\\u{1F3CD}", emoji: "🏍️", shortcode: ":motorb:" },
      { unicode: "\\u{1F690}", emoji: "🚐", shortcode: ":van:" },
      { unicode: "\\u{1F69B}", emoji: "🛻", shortcode: ":truck:" },
      { unicode: "\\u{1F69A}", emoji: "🚚", shortcode: ":delivery:" },
      { unicode: "\\u{1F69C}", emoji: "🚛", shortcode: ":lorry:" },
      { unicode: "\\u{1F69C}", emoji: "🚜", shortcode: ":tractor:" },
      { unicode: "\\u{1F6B2}", emoji: "🚲", shortcode: ":bike:" },
      { unicode: "\\u{1F6F4}", emoji: "🛴", shortcode: ":scooter:" },
      { unicode: "\\u{1F6F9}", emoji: "🛹", shortcode: ":skate:" },
      { unicode: "\\u{1F6FC}", emoji: "🛼", shortcode: ":rollers:" },
      { unicode: "\\u{1F6FA}", emoji: "🛺", shortcode: ":tuktuk:" },
      { unicode: "\\u{1F68F}", emoji: "🚏", shortcode: ":stop:" },
      { unicode: "\\u{26FD}", emoji: "⛽", shortcode: ":fuel:" },
      { unicode: "\\u{1F6A8}", emoji: "🚨", shortcode: ":siren:" },
      { unicode: "\\u{1F6A5}", emoji: "🚥", shortcode: ":light_h:" },
      { unicode: "\\u{1F6A6}", emoji: "🚦", shortcode: ":light_v:" },
      { unicode: "\\u{1F6E3}", emoji: "🛣️", shortcode: ":road:" },
      { unicode: "\\u{1F6E4}", emoji: "🛤️", shortcode: ":rail:" },
      { unicode: "\\u{1F6E2}", emoji: "🛢️", shortcode: ":drum_oil:" },
      { unicode: "\\u{26F5}", emoji: "⛵", shortcode: ":sail:" },
      { unicode: "\\u{1F6A4}", emoji: "🚤", shortcode: ":speed:" },
      { unicode: "\\u{1F6F3}", emoji: "🛳️", shortcode: ":cruise:" },
      { unicode: "\\u{26F4}", emoji: "⛴️", shortcode: ":ferry2:" },
      { unicode: "\\u{1F6E5}", emoji: "🛥️", shortcode: ":yacht:" },
      { unicode: "\\u{1F6A2}", emoji: "🚢", shortcode: ":ship2:" },
      { unicode: "\\u{2708}", emoji: "✈️", shortcode: ":plane:" },
      { unicode: "\\u{1F6E9}", emoji: "🛩️", shortcode: ":small_plane:" },
      { unicode: "\\u{1F6EB}", emoji: "🛫", shortcode: ":depart:" },
      { unicode: "\\u{1F6EC}", emoji: "🛬", shortcode: ":arrive:" },
      { unicode: "\\u{1F386}", emoji: "🎆", shortcode: ":firewk:" },
      { unicode: "\\u{1F387}", emoji: "🎇", shortcode: ":sparkle:" },
      { unicode: "\\u{1F303}", emoji: "🌃", shortcode: ":night:" },
      { unicode: "\\u{1F305}", emoji: "🌅", shortcode: ":sunrise:" },
      { unicode: "\\u{1F304}", emoji: "🌄", shortcode: ":mtnsun:" },
      { unicode: "\\u{1F3D4}", emoji: "🏔️", shortcode: ":mount:" },
      { unicode: "\\u{26F0}", emoji: "⛰️", shortcode: ":mt2:" },
      { unicode: "\\u{1F30B}", emoji: "🌋", shortcode: ":volcano:" },
      { unicode: "\\u{1F5FB}", emoji: "🗻", shortcode: ":fuji:" },
      { unicode: "\\u{1F3D6}", emoji: "🏖️", shortcode: ":beach:" },
      { unicode: "\\u{1F3DD}", emoji: "🏝️", shortcode: ":island:" },
      { unicode: "\\u{1F3DC}", emoji: "🏜️", shortcode: ":desert2:" },
      { unicode: "\\u{26F1}", emoji: "⛱️", shortcode: ":umbrella:" },
      { unicode: "\\u{1F3DB}", emoji: "🏛️", shortcode: ":building:" },
    ],
  },
  {
    name: "Objects",
    value: "objects",
    emojis: [
      { unicode: "\\u{231A}", emoji: "⌚", shortcode: ":watch2:" },
      { unicode: "\\u{1F4F1}", emoji: "📱", shortcode: ":phone:" },
      { unicode: "\\u{1F4BB}", emoji: "💻", shortcode: ":laptop2:" },
      { unicode: "\\u{2328}", emoji: "⌨️", shortcode: ":keyboard2:" },
      { unicode: "\\u{1F5A5}", emoji: "🖥️", shortcode: ":desktop2:" },
      { unicode: "\\u{1F5B6}", emoji: "🖨️", shortcode: ":printer2:" },
      { unicode: "\\u{1F5B1}", emoji: "🖱️", shortcode: ":mouse2:" },
      { unicode: "\\u{1F5B2}", emoji: "🖲️", shortcode: ":trackball2:" },
      { unicode: "\\u{1F579}", emoji: "🕹️", shortcode: ":joystick2:" },
      { unicode: "\\u{1F5DC}", emoji: "🗜️", shortcode: ":clamp2:" },
      { unicode: "\\u{1F4BD}", emoji: "💽", shortcode: ":disk:" },
      { unicode: "\\u{1F4BE}", emoji: "💾", shortcode: ":save:" },
      { unicode: "\\u{1F4BF}", emoji: "💿", shortcode: ":cd:" },
      { unicode: "\\u{1F4C0}", emoji: "📀", shortcode: ":dvd2:" },
      { unicode: "\\u{1F3A5}", emoji: "🎥", shortcode: ":camera2:" },
      { unicode: "\\u{1F3AC}", emoji: "🎬", shortcode: ":clapper2:" },
      { unicode: "\\u{1F4F7}", emoji: "📷", shortcode: ":photo:" },
      { unicode: "\\u{1F4F8}", emoji: "📸", shortcode: ":flashcam:" },
      { unicode: "\\u{1F4F9}", emoji: "📹", shortcode: ":videocam:" },
      { unicode: "\\u{1F39E}", emoji: "🎞️", shortcode: ":film:" },
      { unicode: "\\u{1F3A6}", emoji: "🎦", shortcode: ":cinema2:" },
      { unicode: "\\u{1F4FD}", emoji: "📽️", shortcode: ":projector:" },
      { unicode: "\\u{1F50D}", emoji: "🔍", shortcode: ":search:" },
      { unicode: "\\u{1F50E}", emoji: "🔎", shortcode: ":search2:" },
      { unicode: "\\u{1F50F}", emoji: "🔏", shortcode: ":lockpen:" },
      { unicode: "\\u{1F510}", emoji: "🔐", shortcode: ":lockkey:" },
      { unicode: "\\u{1F512}", emoji: "🔒", shortcode: ":locked2:" },
      { unicode: "\\u{1F513}", emoji: "🔓", shortcode: ":unlocked2:" },
      { unicode: "\\u{2697}", emoji: "⚗️", shortcode: ":alembic2:" },
      { unicode: "\\u{1F527}", emoji: "🔧", shortcode: ":wrench2:" },
      { unicode: "\\u{1F528}", emoji: "🔨", shortcode: ":hammer2:" },
      { unicode: "\\u{2692}", emoji: "⚒️", shortcode: ":tools:" },
      { unicode: "\\u{1F6E0}", emoji: "🛠️", shortcode: ":fix:" },
      { unicode: "\\u{26CF}", emoji: "⛏️", shortcode: ":pickaxe2:" },
      { unicode: "\\u{1F529}", emoji: "🔩", shortcode: ":bolt:" },
      { unicode: "\\u{2699}", emoji: "⚙️", shortcode: ":gear2:" },
      { unicode: "\\u{1F9F1}", emoji: "🧱", shortcode: ":brick2:" },
      { unicode: "\\u{26D3}", emoji: "⛓️", shortcode: ":chain2:" },
      { unicode: "\\u{1F9F2}", emoji: "🧲", shortcode: ":magnet2:" },
      { unicode: "\\u{1F52B}", emoji: "🔫", shortcode: ":pistol:" },
      { unicode: "\\u{1F4A3}", emoji: "💣", shortcode: ":bomb2:" },
      { unicode: "\\u{1F52A}", emoji: "🔪", shortcode: ":knife2:" },
      { unicode: "\\u{1F52C}", emoji: "🔬", shortcode: ":micro:" },
      { unicode: "\\u{1F52D}", emoji: "🔭", shortcode: ":telescope2:" },
      { unicode: "\\u{1FA79}", emoji: "🩹", shortcode: ":plaster:" },
      { unicode: "\\u{1FA7A}", emoji: "🩺", shortcode: ":stetho:" },
      { unicode: "\\u{2695}", emoji: "⚕️", shortcode: ":medical:" },
    ],
  },
  {
    name: "Symbols",
    value: "symbols",
    emojis: [
      { unicode: "\\u{2764}", emoji: "❤️", shortcode: ":heart:" },
      { unicode: "\\u{1F9E1}", emoji: "🧡", shortcode: ":oheart:" },
      { unicode: "\\u{1F49B}", emoji: "💛", shortcode: ":yheart:" },
      { unicode: "\\u{1F49A}", emoji: "💚", shortcode: ":gheart:" },
      { unicode: "\\u{1F499}", emoji: "💙", shortcode: ":bheart:" },
      { unicode: "\\u{1F49C}", emoji: "💜", shortcode: ":pheart:" },
      { unicode: "\\u{1F5A4}", emoji: "🖤", shortcode: ":blackhrt:" },
      { unicode: "\\u{1F90D}", emoji: "🤍", shortcode: ":whitehrt:" },
      { unicode: "\\u{1F90E}", emoji: "🤎", shortcode: ":brownhrt:" },
      { unicode: "\\u{1F494}", emoji: "💔", shortcode: ":broken:" },
      { unicode: "\\u{1F495}", emoji: "💕", shortcode: ":hearts:" },
      { unicode: "\\u{1F49E}", emoji: "💞", shortcode: ":revolve:" },
      { unicode: "\\u{1F493}", emoji: "💓", shortcode: ":pulse:" },
      { unicode: "\\u{1F497}", emoji: "💗", shortcode: ":growhrt:" },
      { unicode: "\\u{1F496}", emoji: "💖", shortcode: ":sparklehrt:" },
      { unicode: "\\u{1F498}", emoji: "💘", shortcode: ":cupid2:" },
      { unicode: "\\u{1F49D}", emoji: "💝", shortcode: ":ribbonhrt:" },
      { unicode: "\\u{1F49F}", emoji: "💟", shortcode: ":decohrt:" },
      { unicode: "\\u{1F44B}", emoji: "👋", shortcode: ":wave:" },
      { unicode: "\\u{1F91A}", emoji: "🤚", shortcode: ":backhand:" },
      { unicode: "\\u{1F590}", emoji: "🖐️", shortcode: ":handopen:" },
      { unicode: "\\u{270B}", emoji: "✋", shortcode: ":raised:" },
      { unicode: "\\u{1F596}", emoji: "🖖", shortcode: ":vulcan:" },
      { unicode: "\\u{1F44C}", emoji: "👌", shortcode: ":ok:" },
      { unicode: "\\u{1F90C}", emoji: "🤌", shortcode: ":pinch:" },
      { unicode: "\\u{1F90F}", emoji: "🤏", shortcode: ":tiny:" },
      { unicode: "\\u{270C}", emoji: "✌️", shortcode: ":victory2:" },
      { unicode: "\\u{1F91E}", emoji: "🤞", shortcode: ":crossf:" },
      { unicode: "\\u{1FAF0}", emoji: "🫰", shortcode: ":fingersnap:" },
      { unicode: "\\u{1F91F}", emoji: "🤟", shortcode: ":love_you:" },
      { unicode: "\\u{1F918}", emoji: "🤘", shortcode: ":rock_on:" },
      { unicode: "\\u{1F919}", emoji: "🤙", shortcode: ":hangloose:" },
      { unicode: "\\u{1F44D}", emoji: "👍", shortcode: ":thumbs_up:" },
      { unicode: "\\u{1F44E}", emoji: "👎", shortcode: ":thumbs_dn:" },
      { unicode: "\\u{270A}", emoji: "✊", shortcode: ":fist2:" },
      { unicode: "\\u{1F44A}", emoji: "👊", shortcode: ":punch:" },
      { unicode: "\\u{1F91B}", emoji: "🤛", shortcode: ":left_fist:" },
      { unicode: "\\u{1F91C}", emoji: "🤜", shortcode: ":right_fist:" },
      { unicode: "\\u{1F91D}", emoji: "🤝", shortcode: ":handshake2:" },
      { unicode: "\\u{1F485}", emoji: "💅", shortcode: ":nails:" },
      { unicode: "\\u{1F4AA}", emoji: "💪", shortcode: ":muscle2:" },
      { unicode: "\\u{1F442}", emoji: "👂", shortcode: ":ear2:" },
      { unicode: "\\u{1F443}", emoji: "👃", shortcode: ":nose2:" },
    ],
  },
  {
    name: "Flags",
    value: "flags",
    emojis: [
      { unicode: "\\u{1F1FA}\\u{1F1F8}", emoji: "🇺🇸", shortcode: ":flag_us:" },
      { unicode: "\\u{1F1EC}\\u{1F1E7}", emoji: "🇬🇧", shortcode: ":flag_uk:" },
      { unicode: "\\u{1F1EF}\\u{1F1F5}", emoji: "🇯🇵", shortcode: ":flag_jp:" },
      { unicode: "\\u{1F1F0}\\u{1F1F7}", emoji: "🇰🇷", shortcode: ":flag_kr:" },
      { unicode: "\\u{1F1E8}\\u{1F1F3}", emoji: "🇨🇳", shortcode: ":flag_cn:" },
      { unicode: "\\u{1F1EE}\\u{1F1F3}", emoji: "🇮🇳", shortcode: ":flag_in:" },
      { unicode: "\\u{1F1E9}\\u{1F1EA}", emoji: "🇩🇪", shortcode: ":flag_de:" },
      { unicode: "\\u{1F1EB}\\u{1F1F7}", emoji: "🇫🇷", shortcode: ":flag_fr:" },
      { unicode: "\\u{1F1EE}\\u{1F1F9}", emoji: "🇮🇹", shortcode: ":flag_it:" },
      { unicode: "\\u{1F1EA}\\u{1F1F8}", emoji: "🇪🇸", shortcode: ":flag_es:" },
      { unicode: "\\u{1F1F2}\\u{1F1FD}", emoji: "🇲🇽", shortcode: ":flag_mx:" },
      { unicode: "\\u{1F1E7}\\u{1F1F7}", emoji: "🇧🇷", shortcode: ":flag_br:" },
      { unicode: "\\u{1F1E6}\\u{1F1FA}", emoji: "🇦🇺", shortcode: ":flag_au:" },
      { unicode: "\\u{1F1E8}\\u{1F1E6}", emoji: "🇨🇦", shortcode: ":flag_ca:" },
      { unicode: "\\u{1F1F7}\\u{1F1FA}", emoji: "🇷🇺", shortcode: ":flag_ru:" },
      { unicode: "\\u{1F1F5}\\u{1F1F0}", emoji: "🇵🇰", shortcode: ":flag_pk:" },
      { unicode: "\\u{1F1F3}\\u{1F1EC}", emoji: "🇳🇬", shortcode: ":flag_ng:" },
      { unicode: "\\u{1F1FF}\\u{1F1E6}", emoji: "🇿🇦", shortcode: ":flag_za:" },
      { unicode: "\\u{1F1F5}\\u{1F1EA}", emoji: "🇵🇪", shortcode: ":flag_pe:" },
      { unicode: "\\u{1F1EE}\\u{1F1F1}", emoji: "🇮🇳", shortcode: ":flag_in2:" },
      { unicode: "\\u{1F1F9}\\u{1F1ED}", emoji: "🇹🇭", shortcode: ":flag_th:" },
      { unicode: "\\u{1F1FB}\\u{1F1F3}", emoji: "🇻🇳", shortcode: ":flag_vn:" },
      { unicode: "\\u{1F1F5}\\u{1F1EA}", emoji: "🇵🇭", shortcode: ":flag_ph:" },
      { unicode: "\\u{1F1F2}\\u{1F1FE}", emoji: "🇲🇾", shortcode: ":flag_my:" },
      { unicode: "\\u{1F1F8}\\u{1F1EC}", emoji: "🇸🇬", shortcode: ":flag_sg:" },
      { unicode: "\\u{1F1EE}\\u{1F1E9}", emoji: "🇮🇩", shortcode: ":flag_id:" },
      { unicode: "\\u{1F1F9}\\u{1F1FC}", emoji: "🇹🇼", shortcode: ":flag_tw:" },
      { unicode: "\\u{1F1ED}\\u{1F1F0}", emoji: "🇭🇰", shortcode: ":flag_hk:" },
      { unicode: "\\u{1F1F6}\\u{1F1E6}", emoji: "🇶🇦", shortcode: ":flag_qa:" },
      { unicode: "\\u{1F1F8}\\u{1F1E6}", emoji: "🇸🇦", shortcode: ":flag_sa:" },
      { unicode: "\\u{1F1E6}\\u{1F1EA}", emoji: "🇦🇪", shortcode: ":flag_ae:" },
      { unicode: "\\u{1F1EE}\\u{1F1F1}", emoji: "🇮🇱", shortcode: ":flag_il:" },
      { unicode: "\\u{1F1F0}\\u{1F1EA}", emoji: "🇰🇪", shortcode: ":flag_ke:" },
      { unicode: "\\u{1F1F3}\\u{1F1FF}", emoji: "🇳🇿", shortcode: ":flag_nz:" },
      { unicode: "\\u{1F1EB}\\u{1F1EE}", emoji: "🇫🇮", shortcode: ":flag_fi:" },
      { unicode: "\\u{1F1E8}\\u{1F1ED}", emoji: "🇨🇭", shortcode: ":flag_ch:" },
      { unicode: "\\u{1F1E6}\\u{1F1F9}", emoji: "🇦🇹", shortcode: ":flag_at:" },
      { unicode: "\\u{1F1E7}\\u{1F1EA}", emoji: "🇧🇪", shortcode: ":flag_be:" },
      { unicode: "\\u{1F1F1}\\u{1F1FA}", emoji: "🇱🇺", shortcode: ":flag_lu:" },
      { unicode: "\\u{1F1F5}\\u{1F1F9}", emoji: "🇵🇹", shortcode: ":flag_pt:" },
      { unicode: "\\u{1F1EE}\\u{1F1EA}", emoji: "🇮🇪", shortcode: ":flag_ie:" },
      {
        unicode: "\\u{1F3F3}\\u{FE0F}\\u{200D}\\u{1F308}",
        emoji: "🏳️‍🌈",
        shortcode: ":pride:",
      },
      { unicode: "\\u{1F3F4}", emoji: "🏴", shortcode: ":black_flag:" },
      { unicode: "\\u{1F3F3}", emoji: "🏳️", shortcode: ":white_flag2:" },
    ],
  },
];

export default emojiArray;
